---
title: "Muddy Points"
subtitle: "Lesson 12: Interactions, Part 2"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Muddy Points from Winter 2025

## Muddy Points from Winter 2024

### 1. Interactions in general

#### 1.1 Why is it not an effect modifier if p-value is 0.4? Or why is it not significant? Is it because it is not = 0?

#### 1.2 What are some reasons why we would think an effect modifier might exist in our data? or are we testing indiscriminately/ based on our own perspective of the associations in the data

#### 1.3 I'm still not entirely sure I know how to do all the steps of interaction models, but I think part of that may just be me needing to look at my previous notes.

### 2. Centering the continuous covariate

#### 2.1 How does centering help with interpretation?

I think [this blog post](https://www.theanalysisfactor.com/when-not-to-center-a-predictor-variable-in-regression/) has a nice explanation.

But for an example from our class... centering female literacy rate can help us interpret the... randomly stopped typing...

#### 2.2 Why do some values of $\beta$ change after centering the mean and others don't?

```{r}
#| echo: false

g=3
```
