---
title: "Homework"
format: 
  html:
    page-layout: full
    link-external-newwindow: true
    toc: false
---

+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| Homework | Assignment                                                                                             | Assignment due (\@11pm) | Answers                                                         | Solutions (`.qmd`)                                                              | Solutions (`.html`)\*                                                 |
+==========+========================================================================================================+=========================+=================================================================+=================================================================================+=======================================================================+
| 0        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_00.qmd)]{style="color:#f8f5f0;"} | 1/9                     | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 1        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_01.qmd)]{style="color:#f8f5f0;"} | 1/23                    | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 2        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_02.qmd)]{style="color:#f8f5f0;"} | 1/30                    | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 3        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_03.qmd)]{style="color:#f8f5f0;"} | 2/13                    | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 4        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_04.qmd)]{style="color:#f8f5f0;"} | 2/20                    | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 5        | [[{{< iconify material-symbols assignment size=29px >}}](/homework/HW_05.qmd)]{style="color:#f8f5f0;"} | 3/6                     | [{{< iconify ph key-fill size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify icon-park-twotone file-code size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify mingcute web-fill size=29px >}}]{style="color:#f8f5f0;"} |
+----------+--------------------------------------------------------------------------------------------------------+-------------------------+-----------------------------------------------------------------+---------------------------------------------------------------------------------+-----------------------------------------------------------------------+

Please note that you need to download the `.html` file to see the LaTeX math properly.

## File Naming

-   For HW **Assignments**, please use the following file naming: "HW01_LastName_FirstInitial"

    -   For homeworks without R, this should be a **pdf file**

    -   For homeworks with R, this should be an **html file**

## Rubrics

+---------------------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|                           | 1 point                                                                                                 | 0.5 points                                                                            | 0 points                                                                               |
+===========================+=========================================================================================================+=======================================================================================+========================================================================================+
| Accuracy                  | All calculations and answers are correct, with clear and logical steps                                  | Minor errors in calculations or reasoning, but most concepts are applied correctly    | Major mistakes or incorrect application of statistical methods                         |
+---------------------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Understanding of concepts | Demonstrates strong understanding of statistical concepts and their application                         | Some understanding, but with gaps or misconceptions about certain concepts            | Little or no understanding of the key statistical ideas                                |
+---------------------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Presentation and clarity  | Homework is well-organized, legible, and easy to follow, with clear explanations of steps and reasoning | Work is somewhat disorganized or unclear, but the main points can still be understood | Poorly organized or difficult to understand, with little to no explanation of the work |
+---------------------------+---------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
