---
title: "Project Central"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
  pdf: default
editor_options: 
  chunk_output_type: console
---

```{css, echo=FALSE}
.title{
  font-size: 40px;
  color: #213c96;
  background-color: #fff;
  padding: 0px;
}
```

## Labs

| Lab | Due Date | Topics |
|--------------------|------------------|----------------------------------|
| [Lab 1](/labs/Lab_01_instructions.qmd) | 1/16 | Exploring the question |
| [Lab 2](/labs/Lab_02_instructions.qmd) | 2/7 | Exploring the data |
| [Lab 3](/labs/Lab_03_work.qmd) | 2/28 | A little more data exploration + Fitting and interpreting a model |
| [Lab 4](/labs/Lab_04_instructions.qmd) | 3/14 | Building a model |

-   [Help with BMI variable](/labs/BMI_help.qmd)

## Poster and presentation

[Last Year's Report Instructions](/labs/Project_report_instructions.qmd)

-   I am currently updating the Poster instructions

Poster due 3/17

```{r}
#| echo: false
g=3
```

### Reading and listening sources

If you are interested in sources that discuss the social complexities of anti-fat bias, feel free to take a look at the following sources. **Please be aware that these resources will discuss anti-fat bias and related histories, including racism and sexism.**

-   Article: [Implicit and explicit anti-fat bias: The role of weight-related attitudes and beliefs](./resources/Implicit_anti_fat.pdf)

-   Podcast: [Anti-Fat Bias by Maintenance Phase](https://maintenancephase.buzzsprout.com/1411126/6524683-anti-fat-bias)

-   Book: Fearing the Black Body: The Racial Origins of Fat Phobia

    -   Multnomah County Library has unlimited loans for the audiobook

-   Blog: [Dances with Fat](https://danceswithfat.org/)

    -   You can subscribe to Ragen's weekly newsletter for free

If you have additional sources that you would like to share, please send them to me!

## Lab rubric

|   | 4 points | 3 points | 2 points | 1 point | 0 points |
|------------|------------|------------|------------|------------|------------|
| Formatting | Lab submitted on Sakai with `.html` file. Answers are written as asked (bullets or complete sentences) with no major grammatical nor spelling errors. With little editing, the answer can be incorporated into the project poster. | Lab submitted on Sakai with `.html` file. Answers are written as asked (bullets or complete sentences) with grammatical or spelling errors. With editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are written as asked (bullets or complete sentences) with major grammatical or spelling errors. With major editing, the answer can be incorporated into the project report. | Lab submitted on Sakai with `.html` file. Answers are not written as asked. | Lab *not* submitted on Sakai with `.html` file. |
| Code/Work\* | All tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output. | All tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output. In a few tasks, the code syntax or output is not quite right. | Some tasks are directly followed or answered. This includes all the needed code, in code chunks, with the requested output. | Some tasks are directly followed or answered.This includes all the needed code, in code chunks, with the requested output. In a few tasks, the code syntax or output is not quite right. | More than a quarter of the tasks are not completed properly. |
| Reasoning\*\* | Answers demonstrate understanding of research context and investigation of the data. Answers are thoughtful and can be easily integrated into the final report. | Answers demonstrate understanding of research context and investigation of the data. Answers are thoughtful, but lack the clarity needed to easily integrate into the final report. | Answers demonstrate some understanding of research context and investigation of the data. Answers are fairly thoughtful, but lack connection to the research. | Answers demonstrate some understanding of research context and investigation of the data. Answers seem rushed and with minimal thought. | Answers lack understanding of research context and investigation of the data. Answers seem rushed and without thought. |

\*While there is not a large emphasis on "correctness" in the labs, you must follow the correct procedure for certain tasks. The code/work grade will reflect whether or not you followed the procedure for analysis correctly.

\*\*Applies to questions with reasoning (like target population, choosing variables, revisiting research question)
