---
title: "Schedule"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

| Week | Date | Les-son | Topic | [TB 1](https://jfrench.github.io/LinearRegression/) | [TB 2](https://bookdown.org/rwnahhas/RMPH/) | Key Info | Slides HTML | Slides PDF | Slides Notes | Exit tix | Record-ing | Muddy Points |
|------|------|------|------|------|------|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 1 | 1/6 | 0 | Welcome |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Welcome/00_Welcome_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Welcome/00_Welcome.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Welcome/00_Welcome.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUN1BGMlMzNUVTTkwyQzRRN0NUUzNNT0hRTC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-06T13:00:00.000_2025-01-06T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 1 | Review |  |  |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Review/01_Review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Review/01_Review.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/01_Review/01_Review_notes.pdf)]{style="color:#f8f5f0;"} |  |  | [[{{< iconify pajamas question size=30px >}}](lessons/01_Review/01_Review_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 1/8 | 2 | Data and File Management |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Data_Management/02_Data_Management_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Data_Management/02_Data_Management.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Data_Management/02_Data_Management.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/02_Data_Management/02_Data_Management_notes.pdf)]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-08T13:00:00.000_2025-01-08T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**1/9**]{style="color:#213c96;"} |  | [**HW 0 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 2 | 1/13 | 3 | Simple Linear Regression | 3.1-3.2, 3.4 | 4.1-4.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/03_SLR/03_SLR_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_SLR/03_SLR.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_SLR/03_SLR.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/03_SLR/03_SLR_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURTlXSkdCUzZSUVhLUUI4QkdSNUhVVEtXSi4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-13T13:00:00.000_2025-01-13T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/03_SLR/03_SLR_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 1/15 | 4 | SLR: Inference and Prediction | 3.3 | 4.3, 4.5-4.7 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMlNKSEk3QjhMTVlXRVI5UE0yNTdZMk5FSC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-15T13:00:00.000_2025-01-15T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/04_SLR_Inf_Pred/04_SLR_Inf_Pred_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**1/16**]{style="color:#213c96;"} |  | [**Lab 1 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 3 | 1/20 |  | No Class, MLKJ Day |  |  |  |  |  |  |  |  |  |
|  | 1/22 | 5 | SLR: Categorical Covariates | 3.8-3.9 | 4.4 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/05_Cat_covariates/05_Cat_covariates_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Cat_covariates/05_Cat_covariates.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_Cat_covariates/05_Cat_covariates.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/05_Cat_covariates/05_Cat_covariates_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQzFXVlNYV1oyWEQ4OEVQSk5NSU0zNlcwMS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-22T13:00:00.000_2025-01-22T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/05_Cat_covariates/05_Cat_covariates_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**1/23**]{style="color:#213c96;"} |  | [**HW 1 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 4 | 1/27 | 6 | SLR: More inference | 6.10 | NA | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/06_SLR_Eval/06_SLR_Eval_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/06_SLR_Eval/06_SLR_Eval.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/06_SLR_Eval/06_SLR_Eval.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/06_SLR_Eval/06_SLR_Eval_notes.pdf)[{{\< iconify pepicons-pop pen-circle-filled size=29px \>}}](lessons/06_SLR_E06_Extra_viz_total_variation.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUMVIzRzU1T1oyQlhLSzZENU05WlRMME1PTS4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-27T13:00:00.000_2025-01-27T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/06_SLR_Eval/06_SLR_Eval_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 1/29 | 7 | SLR: Checking model assumptions | 5.1-5.2 | 5.13-5.17 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUREVPWDI0WkxDMDFJNTRUQjdLRjg0WEhaRC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-01-29T13:00:00.000_2025-01-29T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/07_SLR_Assumptions/07_SLR_Assumptions_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**1/31**]{style="color:#213c96;"} |  | [**HW 2 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 5 | 2/3 | 8 | SLR: Diagnostics |  | 5.21-5.22, 5.25.2 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURjNSVENTWFBNSlpYQlUyU09PMFNHVVZQOC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-02-03T13:00:00.000_2025-02-03T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/08_SLR_Diagnostics/08_SLR_Diag_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | 2/5 | 9 | Multiple Linear Regression | 3.5-3.6, 4.1 | 5.1-5.2, 5.5-5.6 | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/09_MLR_Intro/09_MLR_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_MLR_Intro/09_MLR_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_MLR_Intro/09_MLR_Intro.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/09_MLR_Intro/09_MLR_Intro_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhURFczQUI1MEtQRTc4TVlGVU05Q1ZLRk5JWi4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_bd258b2c-7ce0-48ef-99a4-fa711a53c5ed_6e6935cc-2428-4a3e-842c-537121bffd64_2025-02-05T13:00:00.000_2025-02-05T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [[{{< iconify pajamas question size=30px >}}](lessons/09_MLR_Intro/09_MLR_Intro_muddy_points.qmd)]{style="color:#f8f5f0;"} |
|  | [**2/7**]{style="color:#213c96;"} |  | [**Lab 2 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 6 | 2/10 | 10 | MLR: Using the F-test |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/10_MLR_F-test/10_MLR_F-test_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_MLR_F-test/10_MLR_F-test.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_MLR_F-test/10_MLR_F-test.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOVJHSVA5M1Y3VFRWSkQ2WU5WMzlVUkRHQy4u)]{style="color:#f8f5f0;"} |  [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_36f61320-d3c4-4021-8ed8-2e672525fe6f_6e6935cc-2428-4a3e-842c-537121bffd64_2025-02-10T13:00:00.000_2025-02-10T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | 2/12 |  | Lab 2 Review |  |  | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/11_Interactions_01/11_Interactions_01_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/Review-slides_HW-Labs/Review_HW_02_Lab_02.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/Review-slides_HW-Labs/Review_HW_02_Lab_02.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/Review-slides_HW-Labs/Review_HW_02_Lab_02_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOEhVNkFDTjlWMDhRR043WFVMVlc0QU5YSC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-02-12T13:00:00.000_2025-02-12T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 11 | Interactions, Part 1 |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Interactions_01/11_Interactions_01.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Interactions_01/11_Interactions_01.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify pepicons-pop pen-circle-filled size=29px >}}](lessons/11_Interactions_01/11_Interactions_01_notes.pdf)]{style="color:#f8f5f0;"} | [[{{< iconify healthicons health-worker-form size=32px >}}](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUOEhVNkFDTjlWMDhRR043WFVMVlc0QU5YSC4u)]{style="color:#f8f5f0;"} | [[{{< iconify mdi video size=34px >}}](https://echo360.org/lesson/G_18132cd0-4a6d-40e2-9368-e67ff10b425e_6e6935cc-2428-4a3e-842c-537121bffd64_2025-02-12T13:00:00.000_2025-02-12T15:00:00.000/classroom#sortDirection=desc)]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**2/14**]{style="color:#213c96;"} |  | [**HW 3 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 7 | 2/17 |  | No Class, President's Day |  |  |  |  |  |  |  |  |  |
|  | 2/19 | 12 | Interactions, Part 2 |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Interactions_02/12_Interactions_02.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**2/21**]{style="color:#213c96;"} |  | [**Lab 3 due \@ 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 8 | 2/24 | 13 | Model Selection |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/13_Model_selection/13_Model_selection.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | 2/26 | 14 | Purposeful Selection |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_Purposeful_selection/14_Purposeful_selection.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**2/28**]{style="color:#213c96;"} |  | [**HW 4 due 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 9 | 3/3 | 15 | MLR: Diagnostics |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_MLR_Diagnostics/15_MLR_Diagnostics.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | 3/5 |  | Catch-up day |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/15_MLR_Diagnostics/15_MLR_Diagnostics.qmd)]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**3/7**]{style="color:#213c96;"} |  | [**Lab 4 due 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 10 | 3/10 |  | Catch-up day |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | 3/12 |  | Catch-up day |  |  | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify ri slideshow-fill size=30px >}}]{style="color:#f8f5f0;"} | [{{< iconify bi file-earmark-pdf-fill size=28px >}}]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**3/14**]{style="color:#213c96;"} |  | [**HW 5 due 11 pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |  |  |
| 11 | 3/17 |  | Project Day!! |  |  |  |  |  |  |  |  |  |
|  | [**3/17**]{style="color:#213c96;"} |  | [**Project due 11pm**]{style="color:#213c96;"} |  |  |  |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 30,8, 8, 6, 6, 6,6, 6\]"}
