<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nicky Wakim">
<meta name="dcterms.date" content="2023-01-17">

<title>Linear Models - Lesson 3: Introduction to Simple Linear Regression (SLR)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-sm navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/bsta_512_hex.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Linear Models</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html" rel="" target="">
 <span class="menu-text">Schedule</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../instructors.html" rel="" target="">
 <span class="menu-text">Instructors</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../homework.html" rel="" target="">
 <span class="menu-text">Homework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../project.html" rel="" target="">
 <span class="menu-text">Project</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#lets-start-with-an-example" id="toc-lets-start-with-an-example" class="nav-link" data-scroll-target="#lets-start-with-an-example">Let’s start with an example</a></li>
  <li><a href="#reference-how-did-i-code-that" id="toc-reference-how-did-i-code-that" class="nav-link" data-scroll-target="#reference-how-did-i-code-that">Reference: How did I code that?</a></li>
  <li><a href="#dataset-description" id="toc-dataset-description" class="nav-link" data-scroll-target="#dataset-description">Dataset description</a></li>
  <li><a href="#get-to-know-the-data-12" id="toc-get-to-know-the-data-12" class="nav-link" data-scroll-target="#get-to-know-the-data-12">Get to know the data (1/2)</a></li>
  <li><a href="#get-to-know-the-data-22" id="toc-get-to-know-the-data-22" class="nav-link" data-scroll-target="#get-to-know-the-data-22">Get to know the data (2/2)</a></li>
  <li><a href="#remove-missing-values-12" id="toc-remove-missing-values-12" class="nav-link" data-scroll-target="#remove-missing-values-12">Remove missing values (1/2)</a></li>
  <li><a href="#remove-missing-values-22" id="toc-remove-missing-values-22" class="nav-link" data-scroll-target="#remove-missing-values-22">Remove missing values (2/2)</a></li>
  <li><a href="#poll-everywhere-question-1" id="toc-poll-everywhere-question-1" class="nav-link" data-scroll-target="#poll-everywhere-question-1">Poll Everywhere Question 1</a></li>
  </ul></li>
  <li><a href="#learning-objectives-1" id="toc-learning-objectives-1" class="nav-link" data-scroll-target="#learning-objectives-1">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#questions-we-can-ask-with-a-simple-linear-regression-model" id="toc-questions-we-can-ask-with-a-simple-linear-regression-model" class="nav-link" data-scroll-target="#questions-we-can-ask-with-a-simple-linear-regression-model">Questions we can ask with a simple linear regression model</a></li>
  <li><a href="#association-vs.-prediction" id="toc-association-vs.-prediction" class="nav-link" data-scroll-target="#association-vs.-prediction">Association vs.&nbsp;prediction</a></li>
  <li><a href="#three-types-of-study-design-there-are-more" id="toc-three-types-of-study-design-there-are-more" class="nav-link" data-scroll-target="#three-types-of-study-design-there-are-more">Three types of study design (there are more)</a></li>
  <li><a href="#lets-revisit-the-regression-analysis-process" id="toc-lets-revisit-the-regression-analysis-process" class="nav-link" data-scroll-target="#lets-revisit-the-regression-analysis-process">Let’s revisit the regression analysis process</a></li>
  <li><a href="#poll-everywhere-question-2" id="toc-poll-everywhere-question-2" class="nav-link" data-scroll-target="#poll-everywhere-question-2">Poll Everywhere Question 2</a></li>
  </ul></li>
  <li><a href="#learning-objectives-2" id="toc-learning-objectives-2" class="nav-link" data-scroll-target="#learning-objectives-2">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-model" id="toc-simple-linear-regression-model" class="nav-link" data-scroll-target="#simple-linear-regression-model">Simple Linear Regression Model</a></li>
  <li><a href="#simple-linear-regression-model-another-way-to-view-components" id="toc-simple-linear-regression-model-another-way-to-view-components" class="nav-link" data-scroll-target="#simple-linear-regression-model-another-way-to-view-components">Simple Linear Regression Model (another way to view components)</a>
  <ul class="collapse">
  <li><a href="#components" id="toc-components" class="nav-link" data-scroll-target="#components">Components</a></li>
  </ul></li>
  <li><a href="#if-the-population-parameters-are-unobservable-how-did-we-get-the-line-for-life-expectancy" id="toc-if-the-population-parameters-are-unobservable-how-did-we-get-the-line-for-life-expectancy" class="nav-link" data-scroll-target="#if-the-population-parameters-are-unobservable-how-did-we-get-the-line-for-life-expectancy">If the population parameters are unobservable, how did we get the line for life expectancy?</a></li>
  <li><a href="#poll-everywhere-question-3" id="toc-poll-everywhere-question-3" class="nav-link" data-scroll-target="#poll-everywhere-question-3">Poll Everywhere Question 3</a></li>
  <li><a href="#okay-so-how-do-we-estimate-the-regression-line" id="toc-okay-so-how-do-we-estimate-the-regression-line" class="nav-link" data-scroll-target="#okay-so-how-do-we-estimate-the-regression-line">Okay, so how do we estimate the regression line?</a></li>
  <li><a href="#regression-line-best-fit-line" id="toc-regression-line-best-fit-line" class="nav-link" data-scroll-target="#regression-line-best-fit-line">Regression line = best-fit line</a></li>
  <li><a href="#simple-linear-regression-model-1" id="toc-simple-linear-regression-model-1" class="nav-link" data-scroll-target="#simple-linear-regression-model-1">Simple Linear Regression Model</a></li>
  <li><a href="#we-get-it-nicky-how-do-we-estimate-the-regression-line" id="toc-we-get-it-nicky-how-do-we-estimate-the-regression-line" class="nav-link" data-scroll-target="#we-get-it-nicky-how-do-we-estimate-the-regression-line">We get it, Nicky! How do we estimate the regression line?</a></li>
  </ul></li>
  <li><a href="#learning-objectives-3" id="toc-learning-objectives-3" class="nav-link" data-scroll-target="#learning-objectives-3">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#it-all-starts-with-a-residual" id="toc-it-all-starts-with-a-residual" class="nav-link" data-scroll-target="#it-all-starts-with-a-residual">It all starts with a residual…</a></li>
  <li><a href="#so-now-we-have-two-representations-of-our-population-model" id="toc-so-now-we-have-two-representations-of-our-population-model" class="nav-link" data-scroll-target="#so-now-we-have-two-representations-of-our-population-model">So now we have two representations of our population model</a></li>
  <li><a href="#back-to-our-estimated-model" id="toc-back-to-our-estimated-model" class="nav-link" data-scroll-target="#back-to-our-estimated-model">Back to our estimated model</a></li>
  <li><a href="#individual-i-residuals-in-the-estimatedfitted-model" id="toc-individual-i-residuals-in-the-estimatedfitted-model" class="nav-link" data-scroll-target="#individual-i-residuals-in-the-estimatedfitted-model"><em>Individual</em> <span class="math inline">\(i\)</span> residuals in the estimated/fitted model</a></li>
  <li><a href="#individual-i-residuals-in-the-estimatedfitted-model-1" id="toc-individual-i-residuals-in-the-estimatedfitted-model-1" class="nav-link" data-scroll-target="#individual-i-residuals-in-the-estimatedfitted-model-1"><em>Individual</em> <span class="math inline">\(i\)</span> residuals in the estimated/fitted model</a></li>
  <li><a href="#poll-everywhere-question-4" id="toc-poll-everywhere-question-4" class="nav-link" data-scroll-target="#poll-everywhere-question-4">Poll Everywhere Question 4</a></li>
  <li><a href="#so-what-do-we-do-with-the-residuals" id="toc-so-what-do-we-do-with-the-residuals" class="nav-link" data-scroll-target="#so-what-do-we-do-with-the-residuals">So what do we do with the residuals?</a></li>
  </ul></li>
  <li><a href="#learning-objectives-4" id="toc-learning-objectives-4" class="nav-link" data-scroll-target="#learning-objectives-4">Learning Objectives</a>
  <ul class="collapse">
  <li><a href="#setting-up-for-ordinary-least-squares" id="toc-setting-up-for-ordinary-least-squares" class="nav-link" data-scroll-target="#setting-up-for-ordinary-least-squares">Setting up for ordinary least squares</a></li>
  <li><a href="#steps-to-estimate-coefficients-using-ols" id="toc-steps-to-estimate-coefficients-using-ols" class="nav-link" data-scroll-target="#steps-to-estimate-coefficients-using-ols">Steps to estimate coefficients using OLS</a></li>
  <li><a href="#minimize-sse-with-respect-to-coefficients" id="toc-minimize-sse-with-respect-to-coefficients" class="nav-link" data-scroll-target="#minimize-sse-with-respect-to-coefficients">2. Minimize SSE with respect to coefficients</a></li>
  <li><a href="#compute-derivative-of-sse-wrt-widehatbeta_0" id="toc-compute-derivative-of-sse-wrt-widehatbeta_0" class="nav-link" data-scroll-target="#compute-derivative-of-sse-wrt-widehatbeta_0">3. Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_0\)</span></a></li>
  <li><a href="#set-derivative-of-sse-wrt-widehatbeta_0-0" id="toc-set-derivative-of-sse-wrt-widehatbeta_0-0" class="nav-link" data-scroll-target="#set-derivative-of-sse-wrt-widehatbeta_0-0">4. Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_0 = 0\)</span></a></li>
  <li><a href="#compute-derivative-of-sse-wrt-widehatbeta_1" id="toc-compute-derivative-of-sse-wrt-widehatbeta_1" class="nav-link" data-scroll-target="#compute-derivative-of-sse-wrt-widehatbeta_1">5. Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_1\)</span></a></li>
  <li><a href="#set-derivative-of-sse-wrt-widehatbeta_1-0" id="toc-set-derivative-of-sse-wrt-widehatbeta_1-0" class="nav-link" data-scroll-target="#set-derivative-of-sse-wrt-widehatbeta_1-0">6. Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_1 = 0\)</span></a></li>
  <li><a href="#substitute-widehatbeta_1-back-into-widehatbeta_0" id="toc-substitute-widehatbeta_1-back-into-widehatbeta_0" class="nav-link" data-scroll-target="#substitute-widehatbeta_1-back-into-widehatbeta_0">7. Substitute <span class="math inline">\(\widehat\beta_1\)</span> back into <span class="math inline">\(\widehat\beta_0\)</span></a>
  <ul class="collapse">
  <li><a href="#final-coefficient-estimates-for-slr" id="toc-final-coefficient-estimates-for-slr" class="nav-link" data-scroll-target="#final-coefficient-estimates-for-slr">Final coefficient estimates for SLR</a></li>
  </ul></li>
  <li><a href="#poll-everywhere-question-5" id="toc-poll-everywhere-question-5" class="nav-link" data-scroll-target="#poll-everywhere-question-5">Poll Everywhere Question 5</a></li>
  <li><a href="#do-i-need-to-do-all-that-work-every-time" id="toc-do-i-need-to-do-all-that-work-every-time" class="nav-link" data-scroll-target="#do-i-need-to-do-all-that-work-every-time">Do I need to do all that work every time??</a></li>
  <li><a href="#regression-in-r-lm" id="toc-regression-in-r-lm" class="nav-link" data-scroll-target="#regression-in-r-lm">Regression in R: <code>lm()</code></a></li>
  <li><a href="#regression-in-r-lm-summary" id="toc-regression-in-r-lm-summary" class="nav-link" data-scroll-target="#regression-in-r-lm-summary">Regression in R: <code>lm()</code> + <code>summary()</code></a></li>
  <li><a href="#regression-in-r-lm-tidy" id="toc-regression-in-r-lm-tidy" class="nav-link" data-scroll-target="#regression-in-r-lm-tidy">Regression in R: <code>lm()</code> + <code>tidy()</code></a></li>
  <li><a href="#how-do-we-interpret-the-coefficients" id="toc-how-do-we-interpret-the-coefficients" class="nav-link" data-scroll-target="#how-do-we-interpret-the-coefficients">How do we interpret the coefficients?</a></li>
  <li><a href="#next-time" id="toc-next-time" class="nav-link" data-scroll-target="#next-time">Next time</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="03_SLR.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lesson 3: Introduction to Simple Linear Regression (SLR)</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Week 1</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nicky Wakim </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 17, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="learning-objectives" class="level1">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Identify the aims of your research and see how they align with the intended purpose of simple linear regression</p></li>
<li><p>Identify the simple linear regression model and define statistics language for key notation</p></li>
<li><p>Illustrate how ordinary least squares (OLS) finds the best model parameter estimates</p></li>
<li><p>Solve the optimal coefficient estimates for simple linear regression using OLS</p></li>
<li><p>Apply OLS in R for simple linear regression of real data</p></li>
</ol>
<section id="lets-start-with-an-example" class="level2">
<h2 class="anchored" data-anchor-id="lets-start-with-an-example">Let’s start with an example</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 188 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): country
dbl (2): life_expectancy_years_2011, female_literacy_rate_2011

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>&nbsp;</p>
<p>Average life expectancy vs.&nbsp;female literacy rate</p>
<p>&nbsp;</p>
<ul>
<li>Each point on the plot is for a different country</li>
</ul>
<p>&nbsp;</p>
<ul>
<li><span class="math inline">\(X\)</span> = country’s adult female literacy rate</li>
</ul>
<p>&nbsp;</p>
<ul>
<li><span class="math inline">\(Y\)</span> = country’s average life expectancy (years)</li>
</ul>
</div>
</div>
<div class="heq">
<p><span class="math display">\[\widehat{\text{life expectancy}} =  50.9 + 0.232\cdot\text{female literacy rate}\]</span></p>
</div>
</section>
<section id="reference-how-did-i-code-that" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="reference-how-did-i-code-that">Reference: How did I code that?</h2>
<p><img src="pause.png" class="absolute" data-top="83%" data-right="0%" width="120" height="120"></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gapm, <span class="fu">aes</span>(<span class="at">x =</span> female_literacy_rate_2011,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> life_expectancy_years_2011)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour=</span><span class="st">"#F14124"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Female literacy rate (%)"</span>, </span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Life expectancy (years)"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Relationship between life expectancy and </span><span class="sc">\n</span><span class="st"> the female literacy rate in 2011"</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">30</span>), </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">25</span>), </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">30</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="dataset-description" class="level2">
<h2 class="anchored" data-anchor-id="dataset-description">Dataset description</h2>
<ul>
<li><p>Data files</p>
<ul>
<li><p>Cleaned: <code>lifeexp_femlit_2011.csv</code></p></li>
<li><p>Needs cleaning: <code>lifeexp_femlit_water_2011.csv</code></p></li>
</ul></li>
<li><p>Data were downloaded from <a href="https://www.gapminder.org/data/" class="uri">Gapminder</a></p></li>
<li><p>2011 is the most recent year with the most complete data</p></li>
<li><p><a href="https://www.gapminder.org/data/documentation/gd004/"><strong>Life expectancy</strong></a> = the average number of years a newborn child would live if current mortality patterns were to stay the same.</p></li>
<li><p><a href="http://data.uis.unesco.org/"><strong>Adult literacy rate</strong></a> is the percentage of people ages 15 and above who can, with understanding, read and write a short, simple statement on their everyday life.</p></li>
</ul>
</section>
<section id="get-to-know-the-data-12" class="level2">
<h2 class="anchored" data-anchor-id="get-to-know-the-data-12">Get to know the data (1/2)</h2>
<ul>
<li>Load data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>gapm_original <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"lifeexp_femlit_water_2011.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 194 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): country, water_2011_quart
dbl (3): life_expectancy_years_2011, female_literacy_rate_2011, water_basic_...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<ul>
<li>Glimpse of the data</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gapm_original)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 194
Columns: 5
$ country                    &lt;chr&gt; "Afghanistan", "Albania", "Algeria", "Andor…
$ life_expectancy_years_2011 &lt;dbl&gt; 56.7, 76.7, 76.7, 82.6, 60.9, 76.9, 76.0, 7…
$ female_literacy_rate_2011  &lt;dbl&gt; 13.0, 95.7, NA, NA, 58.6, 99.4, 97.9, 99.5,…
$ water_basic_source_2011    &lt;dbl&gt; 52.6, 88.1, 92.6, 100.0, 40.3, 97.0, 99.5, …
$ water_2011_quart           &lt;chr&gt; "Q1", "Q2", "Q2", "Q4", "Q1", "Q3", "Q4", "…</code></pre>
</div>
</div>
<ul>
<li>Note the missing values for our variables of interest</li>
</ul>
</section>
<section id="get-to-know-the-data-22" class="level2">
<h2 class="anchored" data-anchor-id="get-to-know-the-data-22">Get to know the data (2/2)</h2>
<ul>
<li>Get a sense of the summary statistics</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>gapm_original <span class="sc">%&gt;%</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(life_expectancy_years_2011, female_literacy_rate_2011) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> life_expectancy_years_2011 female_literacy_rate_2011
 Min.   :47.50              Min.   :13.00            
 1st Qu.:64.30              1st Qu.:70.97            
 Median :72.70              Median :91.60            
 Mean   :70.66              Mean   :81.65            
 3rd Qu.:76.90              3rd Qu.:98.03            
 Max.   :82.90              Max.   :99.80            
 NA's   :7                  NA's   :114              </code></pre>
</div>
</div>
</section>
<section id="remove-missing-values-12" class="level2">
<h2 class="anchored" data-anchor-id="remove-missing-values-12">Remove missing values (1/2)</h2>
<ul>
<li>Remove rows with missing data for life expectancy and female literacy rate</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>gapm <span class="ot">&lt;-</span> gapm_original <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(life_expectancy_years_2011, female_literacy_rate_2011)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(gapm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 80
Columns: 5
$ country                    &lt;chr&gt; "Afghanistan", "Albania", "Angola", "Antigu…
$ life_expectancy_years_2011 &lt;dbl&gt; 56.7, 76.7, 60.9, 76.9, 76.0, 73.8, 71.0, 7…
$ female_literacy_rate_2011  &lt;dbl&gt; 13.0, 95.7, 58.6, 99.4, 97.9, 99.5, 53.4, 9…
$ water_basic_source_2011    &lt;dbl&gt; 52.6, 88.1, 40.3, 97.0, 99.5, 97.8, 96.7, 9…
$ water_2011_quart           &lt;chr&gt; "Q1", "Q2", "Q1", "Q3", "Q4", "Q3", "Q3", "…</code></pre>
</div>
</div>
<ul>
<li>No missing values now for our variables of interest</li>
</ul>
</section>
<section id="remove-missing-values-22" class="level2">
<h2 class="anchored" data-anchor-id="remove-missing-values-22">Remove missing values (2/2)</h2>
<ul>
<li>And no more missing values when we look only at our two variables of interest</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>gapm <span class="sc">%&gt;%</span> <span class="fu">select</span>(life_expectancy_years_2011, female_literacy_rate_2011) <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_summary_stats</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 13
  variable        n   min   max median    q1    q3   iqr   mad  mean    sd    se
  &lt;fct&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 life_expec…    80    48  81.8   72.4  65.9  75.8  9.95  6.30  69.9  7.95 0.889
2 female_lit…    80    13  99.8   91.6  71.0  98.0 27.0  11.4   81.7 22.0  2.45 
# ℹ 1 more variable: ci &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="definition">
<div class="def-title">
<p>Note</p>
</div>
<div class="def-cont">
<ul>
<li>Removing the rows with missing data was not needed to run the regression model.</li>
<li>I did this step since later we will be calculating the standard deviations of the explanatory and response variables for <em>just the values included in the regression model</em>. It’ll be easier to do this if we remove the missing values now.</li>
</ul>
</div>
</div>
</section>
<section id="poll-everywhere-question-1" class="level2">
<h2 class="anchored" data-anchor-id="poll-everywhere-question-1">Poll Everywhere Question 1</h2>
</section>
</section>
<section id="learning-objectives-1" class="level1">
<h1>Learning Objectives</h1>
<div class="lob">
<ol type="1">
<li>Identify the aims of your research and see how they align with the intended purpose of simple linear regression</li>
</ol>
</div>
<ol start="2" type="1">
<li><p>Identify the simple linear regression model and define statistics language for key notation</p></li>
<li><p>Illustrate how ordinary least squares (OLS) finds the best model parameter estimates</p></li>
<li><p>Solve the optimal coefficient estimates for simple linear regression using OLS</p></li>
<li><p>Apply OLS in R for simple linear regression of real data</p></li>
</ol>
<section id="questions-we-can-ask-with-a-simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="questions-we-can-ask-with-a-simple-linear-regression-model">Questions we can ask with a simple linear regression model</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 188 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): country
dbl (2): life_expectancy_years_2011, female_literacy_rate_2011

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li>How do we…
<ul>
<li>calculate slope &amp; intercept?</li>
<li>interpret slope &amp; intercept?</li>
<li>do inference for slope &amp; intercept?
<ul>
<li>CI, p-value</li>
</ul></li>
<li>do prediction with regression line?
<ul>
<li>CI for prediction?</li>
</ul></li>
</ul></li>
<li>Does the model fit the data well?
<ul>
<li>Should we be using a line to model the data?</li>
</ul></li>
<li>Should we add additional variables to the model?
<ul>
<li>multiple/multivariable regression</li>
</ul></li>
</ul>
</div>
</div>
<div class="heq">
<p><span class="math display">\[\widehat{\text{life expectancy}} =  50.9 + 0.232\cdot\text{female literacy rate}\]</span></p>
</div>
</section>
<section id="association-vs.-prediction" class="level2">
<h2 class="anchored" data-anchor-id="association-vs.-prediction">Association vs.&nbsp;prediction</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="proof1">
<div class="proof-title">
<p>Association</p>
</div>
<div class="proof-cont">
<ul>
<li>What is the association between countries’ life expectancy and female literacy rate?</li>
<li>Use the slope of the line or correlation coefficient</li>
</ul>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="definition">
<div class="def-title">
<p>Prediction</p>
</div>
<div class="def-cont">
<ul>
<li>What is the expected average life expectancy for a country with a specified female literacy rate? &nbsp; &nbsp;</li>
</ul>
</div>
</div>
</div>
</div>
<p><span class="math display">\[\widehat{\text{life expectancy}} =  50.9 + 0.232\cdot\text{female literacy rate}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 188 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): country
dbl (2): life_expectancy_years_2011, female_literacy_rate_2011

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="three-types-of-study-design-there-are-more" class="level2">
<h2 class="anchored" data-anchor-id="three-types-of-study-design-there-are-more">Three types of study design (there are more)</h2>
<div class="columns">
<div class="column" style="width:33%;">
<div class="definition">
<div class="def-title">
<p>Experiment</p>
</div>
<div class="def-cont">
<ul>
<li><p>Observational units are randomly assigned to important predictor levels</p>
<ul>
<li><p>Random assignment controls for confounding variables (age, gender, race, etc.)</p></li>
<li><p>“gold standard” for determining causality</p></li>
<li><p>Observational unit is often at the participant-level</p></li>
</ul></li>
</ul>
</div>
</div>
</div><div class="column" style="width:33%;">
<div class="example">
<div class="ex-title">
<p>Quasi-experiment</p>
</div>
<div class="ex-cont">
<ul>
<li><p>Participants are assigned to intervention levels without randomization</p></li>
<li><p>Not common study design</p></li>
</ul>
</div>
</div>
</div><div class="column" style="width:33%;">
<div class="proposition">
<div class="prop-title">
<p>Observational</p>
</div>
<div class="prop-cont">
<ul>
<li><p>No randomization or assignment of intervention conditions</p></li>
<li><p>In general cannot infer causality</p>
<ul>
<li>However, there are casual inference methods…</li>
</ul></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="lets-revisit-the-regression-analysis-process" class="level2">
<h2 class="anchored" data-anchor-id="lets-revisit-the-regression-analysis-process">Let’s revisit the regression analysis process</h2>
<p>&nbsp; &nbsp;</p>
<p><img src="images/arrow2.png" class="absolute img-fluid" data-top="17%" data-right="63.15%" width="155"> <img src="images/arrow2.png" class="absolute img-fluid" data-top="17%" data-right="28.7%" width="155"><img src="images/arrow_back4.png" class="absolute img-fluid" data-top="10%" data-right="30.7%" width="840"></p>
<div class="columns">
<div class="column" style="width:30%;">
<div class="RAP1">
<div class="RAP1-title">
<p>Model Selection</p>
</div>
<div class="RAP1-cont">
<ul>
<li><p>Building a model</p></li>
<li><p>Prediction vs interpretation</p></li>
<li><p>Comparing models</p></li>
</ul>
</div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:30%;">
<div class="RAP2">
<div class="RAP2-title">
<p>Model Fitting</p>
</div>
<div class="RAP2-cont">
<ul>
<li><p>Parameter estimation</p></li>
<li><p>Interpret model parameters</p></li>
<li><p>Hypothesis tests for coefficients</p></li>
<li><p>Categorical covariates</p></li>
<li><p>Interactions</p></li>
</ul>
</div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:30%;">
<div class="RAP3">
<div class="RAP3-title">
<p>Model Evaluation</p>
</div>
<div class="RAP3-cont">
<ul>
<li>Evaluation of full and reduced models</li>
<li>Testing model assumptions</li>
<li>Residuals</li>
<li>Transformations</li>
<li>Influential points</li>
<li>Multicollinearity</li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="poll-everywhere-question-2" class="level2">
<h2 class="anchored" data-anchor-id="poll-everywhere-question-2">Poll Everywhere Question 2</h2>
</section>
</section>
<section id="learning-objectives-2" class="level1">
<h1>Learning Objectives</h1>
<ol type="1">
<li>Identify the aims of your research and see how they align with the intended purpose of simple linear regression</li>
</ol>
<div class="lob">
<ol start="2" type="1">
<li>Identify the simple linear regression model and define statistics language for key notation</li>
</ol>
</div>
<ol start="3" type="1">
<li><p>Illustrate how ordinary least squares (OLS) finds the best model parameter estimates</p></li>
<li><p>Solve the optimal coefficient estimates for simple linear regression using OLS</p></li>
<li><p>Apply OLS in R for simple linear regression of real data</p></li>
</ol>
<section id="simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-model">Simple Linear Regression Model</h2>
<p>The (population) regression model is denoted by:</p>
<p>&nbsp;</p>
<div class="heq">
<p><span class="math display">\[Y =  \beta_0 + \beta_1X + \epsilon\]</span></p>
</div>
<p>&nbsp;</p>
<div class="columns">
<div class="column">
<section id="observable-sample-data" class="level4">
<h4 class="anchored" data-anchor-id="observable-sample-data">Observable sample data</h4>
<ul>
<li><p><span class="math inline">\(Y\)</span> is our dependent variable</p>
<ul>
<li>Aka outcome or response variable</li>
</ul></li>
<li><p><span class="math inline">\(X\)</span> is our independent variable</p>
<ul>
<li>Aka predictor, regressor, exposure variable</li>
</ul></li>
</ul>
</section>
</div><div class="column">
<section id="unobservable-population-parameters" class="level4">
<h4 class="anchored" data-anchor-id="unobservable-population-parameters">Unobservable population parameters</h4>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are <strong>unknown</strong> population parameters</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> (epsilon) is the error about the line</p>
<ul>
<li><p>It is assumed to be a random variable with a…</p>
<ul>
<li><p>Normal distribution with mean 0 and constant variance <span class="math inline">\(\sigma^2\)</span></p></li>
<li><p>i.e.&nbsp;<span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span></p></li>
</ul></li>
</ul></li>
</ul>
</section>
</div>
</div>
</section>
<section id="simple-linear-regression-model-another-way-to-view-components" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-model-another-way-to-view-components">Simple Linear Regression Model (another way to view components)</h2>
<p>The (population) regression model is denoted by:</p>
<p>&nbsp;</p>
<div class="heq">
<p><span class="math display">\[Y =  \beta_0 + \beta_1X + \epsilon\]</span></p>
</div>
<p>&nbsp;</p>
<section id="components" class="level3">
<h3 class="anchored" data-anchor-id="components">Components</h3>
<table class="table">
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y\)</span></td>
<td>response, outcome, dependent variable</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_0\)</span></td>
<td>intercept</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_1\)</span></td>
<td>slope</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X\)</span></td>
<td>predictor, covariate, independent variable</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\epsilon\)</span></td>
<td>residuals, error term</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="if-the-population-parameters-are-unobservable-how-did-we-get-the-line-for-life-expectancy" class="level2">
<h2 class="anchored" data-anchor-id="if-the-population-parameters-are-unobservable-how-did-we-get-the-line-for-life-expectancy">If the population parameters are unobservable, how did we get the line for life expectancy?</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>&nbsp;</p>
<div class="hl">
<p>Note: the <strong>population model is the true, underlying model</strong> that we are trying to estimate using our sample data</p>
<ul>
<li>Our goal in simple linear regression is to estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></li>
</ul>
</div>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 188 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): country
dbl (2): life_expectancy_years_2011, female_literacy_rate_2011

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="poll-everywhere-question-3" class="level2">
<h2 class="anchored" data-anchor-id="poll-everywhere-question-3">Poll Everywhere Question 3</h2>
</section>
<section id="okay-so-how-do-we-estimate-the-regression-line" class="level2">
<h2 class="anchored" data-anchor-id="okay-so-how-do-we-estimate-the-regression-line">Okay, so how do we estimate the regression line?</h2>
<p>&nbsp;</p>
<p>At this point, we are going to move over to an R shiny app that I made.</p>
<p>&nbsp;</p>
<p>Let’s see if we can eyeball the best-fit line!</p>
</section>
<section id="regression-line-best-fit-line" class="level2">
<h2 class="anchored" data-anchor-id="regression-line-best-fit-line">Regression line = best-fit line</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="math display">\[\widehat{Y} = \widehat{\beta}_0 + \widehat{\beta}_1 X \]</span></p>
<ul>
<li><span class="math inline">\(\widehat{Y}\)</span> is the predicted outcome for a specific value of <span class="math inline">\(X\)</span></li>
<li><span class="math inline">\(\widehat{\beta}_0\)</span> is the intercept <em>of the best-fit line</em></li>
<li><span class="math inline">\(\widehat{\beta}_1\)</span> is the slope <em>of the best-fit line</em>, i.e., the increase in <span class="math inline">\(\widehat{Y}\)</span> for every increase of one (unit increase) in <span class="math inline">\(X\)</span>
<ul>
<li>slope = <em>rise over run</em></li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 188 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): country
dbl (2): life_expectancy_years_2011, female_literacy_rate_2011

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 108 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="1056"></p>
</div>
</div>
</div>
</div>
</section>
<section id="simple-linear-regression-model-1" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-model-1">Simple Linear Regression Model</h2>
<div class="columns">
<div class="column" style="width:50%;">
<section id="population-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="population-regression-model">Population regression <em>model</em></h4>
<div class="lob">
<p><span class="math display">\[Y =  \beta_0 + \beta_1X + \epsilon\]</span></p>
</div>
<p>&nbsp;</p>
<section id="components-1" class="level5">
<h5 class="anchored" data-anchor-id="components-1">Components</h5>
<table class="table">
<tbody>
<tr class="odd">
<td><span class="math inline">\(Y\)</span></td>
<td>response, outcome, dependent variable</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta_0\)</span></td>
<td>intercept</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta_1\)</span></td>
<td>slope</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X\)</span></td>
<td>predictor, covariate, independent variable</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\epsilon\)</span></td>
<td>residuals, error term</td>
</tr>
</tbody>
</table>
</section>
</section>
</div><div class="column" style="width:50%;">
<section id="estimated-regression-line" class="level4">
<h4 class="anchored" data-anchor-id="estimated-regression-line">Estimated regression <em>line</em></h4>
<div class="hl">
<p><span class="math display">\[\widehat{Y} =  \widehat{\beta}_0 + \widehat{\beta}_1X\]</span></p>
</div>
<p>&nbsp;</p>
<section id="components-2" class="level5">
<h5 class="anchored" data-anchor-id="components-2">Components</h5>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 70%">
</colgroup>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\widehat{Y}\)</span></td>
<td><em>estimated expected</em> response given predictor <span class="math inline">\(X\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\widehat{\beta}_0\)</span></td>
<td><em>estimated</em> intercept</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\widehat{\beta}_1\)</span></td>
<td><em>estimated</em> slope</td>
</tr>
<tr class="even">
<td><span class="math inline">\(X\)</span></td>
<td>predictor, covariate, independent variable</td>
</tr>
</tbody>
</table>
</section>
</section>
</div>
</div>
</section>
<section id="we-get-it-nicky-how-do-we-estimate-the-regression-line" class="level2">
<h2 class="anchored" data-anchor-id="we-get-it-nicky-how-do-we-estimate-the-regression-line">We get it, Nicky! How do we estimate the regression line?</h2>
<p>First let’s take a break!!</p>
</section>
</section>
<section id="learning-objectives-3" class="level1">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Identify the aims of your research and see how they align with the intended purpose of simple linear regression</p></li>
<li><p>Identify the simple linear regression model and define statistics language for key notation</p></li>
</ol>
<div class="lob">
<ol start="3" type="1">
<li>Illustrate how ordinary least squares (OLS) finds the best model parameter estimates</li>
</ol>
</div>
<ol start="4" type="1">
<li><p>Solve the optimal coefficient estimates for simple linear regression using OLS</p></li>
<li><p>Apply OLS in R for simple linear regression of real data</p></li>
</ol>
<section id="it-all-starts-with-a-residual" class="level2">
<h2 class="anchored" data-anchor-id="it-all-starts-with-a-residual">It all starts with a residual…</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p>Recall, one characteristic of our population model was that the residuals, <span class="math inline">\(\epsilon\)</span>, were Normally distributed: <span class="math inline">\(\epsilon \sim N(0, \sigma^2)\)</span></p></li>
<li><p>In our population regression model, we had: <span class="math display">\[Y =  \beta_0 + \beta_1X + \epsilon\]</span></p></li>
<li><p>We can also take the average (expected) value of the population model</p></li>
<li><p>We take the expected value of both sides and get:</p></li>
</ul>
<p><span class="math display">\[\begin{aligned}
        E[Y] &amp; = E[\beta_0 + \beta_1X + \epsilon] \\
        E[Y] &amp; = E[\beta_0] + E[\beta_1X] + E[\epsilon] \\
        E[Y] &amp; = \beta_0 + \beta_1X + E[\epsilon] \\
        E[Y|X] &amp; = \beta_0 + \beta_1X \\
\end{aligned}\]</span></p>
<ul>
<li>We call <span class="math inline">\(E[Y|X]\)</span> the expected value of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_01/OLSassumptions-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="so-now-we-have-two-representations-of-our-population-model" class="level2">
<h2 class="anchored" data-anchor-id="so-now-we-have-two-representations-of-our-population-model">So now we have two representations of our population model</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="definition">
<div class="def-title">
<p>With observed <span class="math inline">\(Y\)</span> values and residuals:</p>
</div>
<div class="def-cont">
<p><span class="math display">\[Y =  \beta_0 + \beta_1X + \epsilon\]</span></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fact">
<div class="fact-title">
<p>With the population expected value of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>:</p>
</div>
<div class="fact-cont">
<p><span class="math display">\[E[Y|X] = \beta_0 + \beta_1X\]</span></p>
</div>
</div>
</div>
</div>
<p>Using the two forms of the model, we can figure out a formula for our residuals:</p>
<p><span class="math display">\[\begin{aligned}
Y &amp; = (\beta_0 + \beta_1X) + \epsilon \\
Y &amp; = E[Y|X] + \epsilon \\
Y - E[Y|X] &amp; = \epsilon \\
\epsilon &amp; = Y - E[Y|X]
\end{aligned}\]</span></p>
<p>And so we have our <strong>true, population model</strong>, residuals!</p>
<div class="hl">
<p>This is an important fact! For the <strong>population model</strong>, the residuals: <span class="math inline">\(\epsilon = Y - E[Y|X]\)</span></p>
</div>
</section>
<section id="back-to-our-estimated-model" class="level2">
<h2 class="anchored" data-anchor-id="back-to-our-estimated-model">Back to our estimated model</h2>
<p>We have the same two representations of our estimated/fitted model:</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="definition">
<div class="def-title">
<p>With observed values:</p>
</div>
<div class="def-cont">
<p><span class="math display">\[Y =  \widehat{\beta}_0 + \widehat{\beta}_1X + \widehat{\epsilon}\]</span></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fact">
<div class="fact-title">
<p>With the estimated expected value of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>:</p>
</div>
<div class="fact-cont">
<p><span class="math display">\[\begin{aligned}
\widehat{E}[Y|X] &amp; = \widehat{\beta}_0 + \widehat{\beta}_1X \\
\widehat{E[Y|X]} &amp; = \widehat{\beta}_0 + \widehat{\beta}_1X \\
\widehat{Y} &amp; = \widehat{\beta}_0 + \widehat{\beta}_1X \\
\end{aligned}\]</span></p>
</div>
</div>
</div>
</div>
<p>Using the two forms of the model, we can figure out a formula for our estimated residuals:</p>
<p><span class="math display">\[\begin{aligned}
Y &amp; = (\widehat{\beta}_0 + \widehat{\beta}_1X) + \widehat\epsilon \\
Y &amp; = \widehat{Y} + \widehat\epsilon \\
\widehat\epsilon &amp; = Y - \widehat{Y}
\end{aligned}\]</span></p>
<div class="lob">
<p>This is an important fact! For the <strong>estimated/fitted model</strong>, the residuals: <span class="math inline">\(\widehat\epsilon = Y - \widehat{Y}\)</span></p>
</div>
</section>
<section id="individual-i-residuals-in-the-estimatedfitted-model" class="level2">
<h2 class="anchored" data-anchor-id="individual-i-residuals-in-the-estimatedfitted-model"><em>Individual</em> <span class="math inline">\(i\)</span> residuals in the estimated/fitted model</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><strong>Observed values for each individual</strong> <span class="math inline">\(i\)</span>: <span class="math inline">\(Y_i\)</span>
<ul>
<li>Value in the dataset for individual <span class="math inline">\(i\)</span></li>
</ul></li>
<li><strong>Fitted value for each individual</strong> <span class="math inline">\(i\)</span>: <span class="math inline">\(\widehat{Y}_i\)</span>
<ul>
<li>Value that falls on the best-fit line for a specific <span class="math inline">\(X_i\)</span></li>
<li>If two individuals have the same <span class="math inline">\(X_i\)</span>, then they have the same <span class="math inline">\(\widehat{Y}_i\)</span></li>
</ul></li>
</ul>
</div><div class="column" style="width:55%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="individual-i-residuals-in-the-estimatedfitted-model-1" class="level2">
<h2 class="anchored" data-anchor-id="individual-i-residuals-in-the-estimatedfitted-model-1"><em>Individual</em> <span class="math inline">\(i\)</span> residuals in the estimated/fitted model</h2>
<div class="columns">
<div class="column" style="width:45%;">
<ul>
<li><p><strong>Observed values for each individual</strong> <span class="math inline">\(i\)</span>: <span class="math inline">\(Y_i\)</span></p>
<ul>
<li>Value in the dataset for individual <span class="math inline">\(i\)</span></li>
</ul></li>
<li><p><strong>Fitted value for each individual</strong> <span class="math inline">\(i\)</span>: <span class="math inline">\(\widehat{Y}_i\)</span></p>
<ul>
<li>Value that falls on the best-fit line for a specific <span class="math inline">\(X_i\)</span></li>
<li>If two individuals have the same <span class="math inline">\(X_i\)</span>, then they have the same <span class="math inline">\(\widehat{Y}_i\)</span></li>
</ul></li>
</ul>
<div class="hl3">
<ul>
<li><p><strong>Residual for each individual:</strong> <span class="math inline">\(\widehat\epsilon_i = Y_i - \widehat{Y}_i\)</span></p>
<ul>
<li>Difference between the observed and fitted value</li>
</ul></li>
</ul>
</div>
</div><div class="column" style="width:55%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="1056"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="poll-everywhere-question-4" class="level2">
<h2 class="anchored" data-anchor-id="poll-everywhere-question-4">Poll Everywhere Question 4</h2>
</section>
<section id="so-what-do-we-do-with-the-residuals" class="level2">
<h2 class="anchored" data-anchor-id="so-what-do-we-do-with-the-residuals">So what do we do with the residuals?</h2>
<ul>
<li><p>We want to <strong>minimize the residuals</strong></p>
<ul>
<li>Aka minimize the difference between the observed <span class="math inline">\(Y\)</span> value and the estimated expected response given the predictor ( <span class="math inline">\(\widehat{E}[Y|X]\)</span> )</li>
</ul></li>
<li><p><strong>We can use ordinary least squares (OLS) to do this in linear regression!</strong></p></li>
<li><p>Idea behind this: reduce the total error between the fitted line and the observed point (error between is called residuals)</p>
<ul>
<li>Vague use of total error: more precisely, we want to <strong>reduce the sum of squared errors</strong></li>
<li>Think back to my R Shiny app!</li>
<li>We need to mathematically define this!</li>
</ul></li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<ul>
<li><p>Note: there are other ways to estimate the best-fit line!!</p>
<ul>
<li>Example: Maximum likelihood estimation</li>
</ul></li>
</ul>
</section>
</section>
<section id="learning-objectives-4" class="level1">
<h1>Learning Objectives</h1>
<ol type="1">
<li><p>Identify the aims of your research and see how they align with the intended purpose of simple linear regression</p></li>
<li><p>Identify the simple linear regression model and define statistics language for key notation</p></li>
<li><p>Illustrate how ordinary least squares (OLS) finds the best model parameter estimates</p></li>
</ol>
<div class="lob">
<ol start="4" type="1">
<li>Solve the optimal coefficient estimates for simple linear regression using OLS</li>
</ol>
</div>
<ol start="5" type="1">
<li>Apply OLS in R for simple linear regression of real data</li>
</ol>
<section id="setting-up-for-ordinary-least-squares" class="level2">
<h2 class="anchored" data-anchor-id="setting-up-for-ordinary-least-squares">Setting up for ordinary least squares</h2>
<div class="columns">
<div class="column" style="width:75%;">
<ul>
<li>Sum of Squared Errors (SSE)</li>
</ul>
<p><span class="math display">\[ \begin{aligned}
SSE &amp; = \displaystyle\sum^n_{i=1} \widehat\epsilon_i^2 \\
SSE &amp; = \displaystyle\sum^n_{i=1} (Y_i - \widehat{Y}_i)^2 \\
SSE &amp; = \displaystyle\sum^n_{i=1} (Y_i - (\widehat{\beta}_0+\widehat{\beta}_1X_i))^2 \\
SSE &amp; = \displaystyle\sum^n_{i=1} (Y_i - \widehat{\beta}_0-\widehat{\beta}_1X_i)^2
\end{aligned}\]</span></p>
</div><div class="column" style="width:25%;">
<div class="fact">
<div class="fact-title">
<p>Things to use</p>
</div>
<div class="fact-cont">
<ul>
<li><p><span class="math inline">\(\widehat\epsilon_i = Y_i - \widehat{Y}_i\)</span></p></li>
<li><p><span class="math inline">\(\widehat{Y}_i = \widehat\beta_0 + \widehat\beta_1X_i\)</span></p></li>
</ul>
</div>
</div>
</div>
</div>
<div class="hl">
<p>Then we want to find the estimated coefficient values that minimize the SSE!</p>
</div>
</section>
<section id="steps-to-estimate-coefficients-using-ols" class="level2">
<h2 class="anchored" data-anchor-id="steps-to-estimate-coefficients-using-ols">Steps to estimate coefficients using OLS</h2>
<ol type="1">
<li><p>Set up SSE (previous slide)</p></li>
<li><p>Minimize SSE with respect to coefficient estimates</p>
<ul>
<li>Need to solve a system of equations</li>
</ul></li>
<li><p>Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_0\)</span></p></li>
<li><p>Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_0 = 0\)</span></p></li>
<li><p>Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_1\)</span></p></li>
<li><p>Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_1 = 0\)</span></p></li>
<li><p>Substitute <span class="math inline">\(\widehat\beta_1\)</span> back into <span class="math inline">\(\widehat\beta_0\)</span></p></li>
</ol>
</section>
<section id="minimize-sse-with-respect-to-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="minimize-sse-with-respect-to-coefficients">2. Minimize SSE with respect to coefficients</h2>
<ul>
<li><p>Want to minimize with respect to (wrt) the potential coefficient estimates ( <span class="math inline">\(\widehat\beta_0\)</span> and <span class="math inline">\(\widehat\beta_1\)</span>)</p></li>
<li><p>Take derivative of SSE wrt <span class="math inline">\(\widehat\beta_0\)</span> and <span class="math inline">\(\widehat\beta_1\)</span> and set equal to zero to find minimum SSE</p></li>
</ul>
<p><span class="math display">\[
\dfrac{\partial SSE}{\partial \widehat\beta_0} = 0 \text{ and } \dfrac{\partial SSE}{\partial \widehat\beta_1} = 0
\]</span></p>
<ul>
<li>Solve the above system of equations in steps 3-6</li>
</ul>
</section>
<section id="compute-derivative-of-sse-wrt-widehatbeta_0" class="level2">
<h2 class="anchored" data-anchor-id="compute-derivative-of-sse-wrt-widehatbeta_0">3. Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_0\)</span></h2>
<div class="columns">
<div class="column" style="width:80%;">
<p><span class="math display">\[
SSE = \displaystyle\sum^n_{i=1} (Y_i - \widehat{\beta}_0-\widehat{\beta}_1X_i)^2
\]</span></p>
<p><span class="math display">\[\begin{aligned}
\frac{\partial SSE}{\partial{\widehat{\beta}}_0}&amp; =\frac{\partial\sum_{i=1}^{n}\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)^2}{\partial{\widehat{\beta}}_0}=
\sum_{i=1}^{n}\frac{{\partial\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)}^2}{\partial{\widehat{\beta}}_0} \\
&amp; =\sum_{i=1}^{n}{2\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)\left(-1\right)}=\sum_{i=1}^{n}{-2\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)} \\
\frac{\partial SSE}{\partial{\widehat{\beta}}_0} &amp; = -2\sum_{i=1}^{n}\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)
\end{aligned}\]</span></p>
</div><div class="column" style="width:20%;">
<div class="fact">
<div class="fact-title">
<p>Things to use</p>
</div>
<div class="fact-cont">
<ul>
<li><p>Derivative rule: derivative of sum is sum of derivative</p></li>
<li><p>Derivative rule: chain rule</p></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="set-derivative-of-sse-wrt-widehatbeta_0-0" class="level2">
<h2 class="anchored" data-anchor-id="set-derivative-of-sse-wrt-widehatbeta_0-0">4. Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_0 = 0\)</span></h2>
<div class="columns">
<div class="column" style="width:75%;">
<p><span class="math display">\[\begin{aligned}
\frac{\partial SSE}{\partial{\widehat{\beta}}_0} &amp; =0 \\ -2\sum_{i=1}^{n}\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right) &amp; =0 \\
\sum_{i=1}^{n}\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right) &amp; =0 \\ \sum_{i=1}^{n}Y_i-n{\widehat{\beta}}_0-{\widehat{\beta}}_1\sum_{i=1}^{n}X_i &amp; =0 \\
\frac{1}{n}\sum_{i=1}^{n}Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1\frac{1}{n}\sum_{i=1}^{n}X_i &amp; =0 \\
\overline{Y}-{\widehat{\beta}}_0-{\widehat{\beta}}_1\overline{X} &amp; =0 \\
{\widehat{\beta}}_0 &amp; =\overline{Y}-{\widehat{\beta}}_1\overline{X}
\end{aligned}\]</span></p>
</div><div class="column" style="width:25%;">
<div class="fact">
<div class="fact-title">
<p>Things to use</p>
</div>
<div class="fact-cont">
<ul>
<li><span class="math inline">\(\overline{Y}=\frac{1}{n}\sum_{i=1}^{n}Y_i\)</span></li>
<li><span class="math inline">\(\overline{X}=\frac{1}{n}\sum_{i=1}^{n}X_i\)</span></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="compute-derivative-of-sse-wrt-widehatbeta_1" class="level2">
<h2 class="anchored" data-anchor-id="compute-derivative-of-sse-wrt-widehatbeta_1">5. Compute derivative of SSE wrt <span class="math inline">\(\widehat\beta_1\)</span></h2>
<div class="columns">
<div class="column" style="width:80%;">
<p><span class="math display">\[
SSE = \displaystyle\sum^n_{i=1} (Y_i - \widehat{\beta}_0-\widehat{\beta}_1X_i)^2
\]</span></p>
<p><span class="math display">\[\begin{aligned}
\frac{\partial SSE}{\partial{\widehat{\beta}}_1}&amp; =\frac{\partial\sum_{i=1}^{n}{(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i)}^2}{\partial{\widehat{\beta}}_1}=\sum_{i=1}^{n}\frac{{\partial(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i)}^2}{\partial{\widehat{\beta}}_1} \\
&amp;=\sum_{i=1}^{n}{2\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)(-X_i)}=\sum_{i=1}^{n}{-2X_i\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)} \\ &amp;=-2\sum_{i=1}^{n}{X_i\left(Y_i-{\widehat{\beta}}_0-{\widehat{\beta}}_1X_i\right)}
\end{aligned}\]</span></p>
</div><div class="column" style="width:20%;">
<div class="fact">
<div class="fact-title">
<p>Things to use</p>
</div>
<div class="fact-cont">
<ul>
<li><p>Derivative rule: derivative of sum is sum of derivative</p></li>
<li><p>Derivative rule: chain rule</p></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="set-derivative-of-sse-wrt-widehatbeta_1-0" class="level2">
<h2 class="anchored" data-anchor-id="set-derivative-of-sse-wrt-widehatbeta_1-0">6. Set derivative of SSE wrt <span class="math inline">\(\widehat\beta_1 = 0\)</span></h2>
<div class="columns">
<div class="column" style="width:70%;">
<p><span class="math display">\[\begin{aligned}
\frac{\partial SSE}{\partial{\widehat{\beta}}_1} &amp; =0 \\ \sum_{i=1}^{n}\left({X_iY}_i-{\widehat{\beta}}_0X_i-{\widehat{\beta}}_1{X_i}^2\right)&amp;=0 \\
\sum_{i=1}^{n}{X_iY_i}-\sum_{i=1}^{n}{X_i{\widehat{\beta}}_0}-\sum_{i=1}^{n}{{X_i}^2{\widehat{\beta}}_1}&amp;=0 \\
\sum_{i=1}^{n}{X_iY_i}-\sum_{i=1}^{n}{X_i\left(\overline{Y}-{\widehat{\beta}}_1\overline{X}\right)}-\sum_{i=1}^{n}{{X_i}^2{\widehat{\beta}}_1} &amp;=0 \\
\sum_{i=1}^{n}{X_iY_i}-\sum_{i=1}^{n}{X_i\overline{Y}}+\sum_{i=1}^{n}{{\widehat{\beta}}_1X_i\overline{X}}-\sum_{i=1}^{n}{{X_i}^2{\widehat{\beta}}_1} &amp;=0 \\
\sum_{i=1}^{n}{X_i(Y_i-\overline{Y})}+\sum_{i=1}^{n}{({\widehat{\beta}}_1X_i\overline{X}}-{X_i}^2{\widehat{\beta}}_1) &amp;=0 \\
\sum_{i=1}^{n}{X_i(Y_i-\overline{Y})}+{\widehat{\beta}}_1\sum_{i=1}^{n}{X_i(\overline{X}}-X_i) &amp;=0 \\
\end{aligned}\]</span></p>
</div><div class="column" style="width:30%;">
<div class="fact">
<div class="fact-title">
<p>Things to use</p>
</div>
<div class="fact-cont">
<ul>
<li><span class="math inline">\({\widehat{\beta}}_0=\overline{Y}-{\widehat{\beta}}_1\overline{X}\)</span></li>
<li><span class="math inline">\(\overline{Y}=\frac{1}{n}\sum_{i=1}^{n}Y_i\)</span></li>
<li><span class="math inline">\(\overline{X}=\frac{1}{n}\sum_{i=1}^{n}X_i\)</span></li>
</ul>
</div>
</div>
<p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
<p>&nbsp;</p>
<div class="heq">
<p><span class="math display">\[{\widehat{\beta}}_1 =\frac{\sum_{i=1}^{n}{X_i(Y_i-\overline{Y})}}{\sum_{i=1}^{n}{X_i(}X_i-\overline{X})}\]</span></p>
</div>
</div>
</div>
</section>
<section id="substitute-widehatbeta_1-back-into-widehatbeta_0" class="level2">
<h2 class="anchored" data-anchor-id="substitute-widehatbeta_1-back-into-widehatbeta_0">7. Substitute <span class="math inline">\(\widehat\beta_1\)</span> back into <span class="math inline">\(\widehat\beta_0\)</span></h2>
<section id="final-coefficient-estimates-for-slr" class="level3">
<h3 class="anchored" data-anchor-id="final-coefficient-estimates-for-slr">Final coefficient estimates for SLR</h3>
<div class="columns">
<div class="column" style="width:50%;">
<div class="proof1">
<div class="proof-title">
<p>Coefficient estimate for <span class="math inline">\(\widehat\beta_1\)</span></p>
</div>
<div class="proof-cont">
<p><span class="math display">\[{\widehat{\beta}}_1 =\frac{\sum_{i=1}^{n}{X_i(Y_i-\overline{Y})}}{\sum_{i=1}^{n}{X_i(}X_i-\overline{X})}\]</span></p>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="fact">
<div class="fact-title">
<p>Coefficient estimate for <span class="math inline">\(\widehat\beta_0\)</span></p>
</div>
<div class="fact-cont">
<p><span class="math display">\[\begin{aligned}
{\widehat{\beta}}_0 &amp; =\overline{Y}-{\widehat{\beta}}_1\overline{X} \\
{\widehat{\beta}}_0 &amp; = \overline{Y} - \frac{\sum_{i=1}^{n}{X_i(Y_i-\overline{Y})}}{\sum_{i=1}^{n}{X_i(}X_i-\overline{X})} \overline{X} \\
\end{aligned}\]</span></p>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="poll-everywhere-question-5" class="level2">
<h2 class="anchored" data-anchor-id="poll-everywhere-question-5">Poll Everywhere Question 5</h2>
</section>
<section id="do-i-need-to-do-all-that-work-every-time" class="level2">
<h2 class="anchored" data-anchor-id="do-i-need-to-do-all-that-work-every-time">Do I need to do all that work every time??</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_01/hoopla.jpeg" class="img-fluid figure-img"></p>
</figure>
</div>
</section>
<section id="regression-in-r-lm" class="level2">
<h2 class="anchored" data-anchor-id="regression-in-r-lm">Regression in R: <code>lm()</code></h2>
<ul>
<li>Let’s discuss the syntax of this function</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy_years_2011 <span class="sc">~</span> female_literacy_rate_2011,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> gapm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regression-in-r-lm-summary" class="level2">
<h2 class="anchored" data-anchor-id="regression-in-r-lm-summary">Regression in R: <code>lm()</code> + <code>summary()</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life_expectancy_years_2011 <span class="sc">~</span> female_literacy_rate_2011,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> gapm)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life_expectancy_years_2011 ~ female_literacy_rate_2011, 
    data = gapm)

Residuals:
    Min      1Q  Median      3Q     Max 
-22.299  -2.670   1.145   4.114   9.498 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               50.92790    2.66041  19.143  &lt; 2e-16 ***
female_literacy_rate_2011  0.23220    0.03148   7.377  1.5e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.142 on 78 degrees of freedom
  (108 observations deleted due to missingness)
Multiple R-squared:  0.4109,    Adjusted R-squared:  0.4034 
F-statistic: 54.41 on 1 and 78 DF,  p-value: 1.501e-10</code></pre>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="03_SLR_01/summary.png" class="img-fluid figure-img"></p>
</figure>
</div>
</section>
<section id="regression-in-r-lm-tidy" class="level2">
<h2 class="anchored" data-anchor-id="regression-in-r-lm-tidy">Regression in R: <code>lm()</code> + <code>tidy()</code></h2>
<p>&nbsp;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model1) <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(<span class="at">table.font.size =</span> <span class="dv">45</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div id="jktykrmlbw" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#jktykrmlbw table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#jktykrmlbw thead, #jktykrmlbw tbody, #jktykrmlbw tfoot, #jktykrmlbw tr, #jktykrmlbw td, #jktykrmlbw th {
  border-style: none;
}

#jktykrmlbw p {
  margin: 0;
  padding: 0;
}

#jktykrmlbw .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 45px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#jktykrmlbw .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#jktykrmlbw .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#jktykrmlbw .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#jktykrmlbw .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jktykrmlbw .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jktykrmlbw .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#jktykrmlbw .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#jktykrmlbw .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#jktykrmlbw .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#jktykrmlbw .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#jktykrmlbw .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#jktykrmlbw .gt_spanner_row {
  border-bottom-style: hidden;
}

#jktykrmlbw .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#jktykrmlbw .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#jktykrmlbw .gt_from_md > :first-child {
  margin-top: 0;
}

#jktykrmlbw .gt_from_md > :last-child {
  margin-bottom: 0;
}

#jktykrmlbw .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#jktykrmlbw .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#jktykrmlbw .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#jktykrmlbw .gt_row_group_first td {
  border-top-width: 2px;
}

#jktykrmlbw .gt_row_group_first th {
  border-top-width: 2px;
}

#jktykrmlbw .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jktykrmlbw .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#jktykrmlbw .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#jktykrmlbw .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jktykrmlbw .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#jktykrmlbw .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#jktykrmlbw .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#jktykrmlbw .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#jktykrmlbw .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#jktykrmlbw .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jktykrmlbw .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jktykrmlbw .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#jktykrmlbw .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#jktykrmlbw .gt_left {
  text-align: left;
}

#jktykrmlbw .gt_center {
  text-align: center;
}

#jktykrmlbw .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#jktykrmlbw .gt_font_normal {
  font-weight: normal;
}

#jktykrmlbw .gt_font_bold {
  font-weight: bold;
}

#jktykrmlbw .gt_font_italic {
  font-style: italic;
}

#jktykrmlbw .gt_super {
  font-size: 65%;
}

#jktykrmlbw .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#jktykrmlbw .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#jktykrmlbw .gt_indent_1 {
  text-indent: 5px;
}

#jktykrmlbw .gt_indent_2 {
  text-indent: 10px;
}

#jktykrmlbw .gt_indent_3 {
  text-indent: 15px;
}

#jktykrmlbw .gt_indent_4 {
  text-indent: 20px;
}

#jktykrmlbw .gt_indent_5 {
  text-indent: 25px;
}

#jktykrmlbw .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#jktykrmlbw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="term">term</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="estimate">estimate</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="std.error">std.error</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="statistic">statistic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="p.value">p.value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="term" class="gt_row gt_left">(Intercept)</td>
<td headers="estimate" class="gt_row gt_right">50.9278981</td>
<td headers="std.error" class="gt_row gt_right">2.66040695</td>
<td headers="statistic" class="gt_row gt_right">19.142898</td>
<td headers="p.value" class="gt_row gt_right">3.325312e-31</td></tr>
    <tr><td headers="term" class="gt_row gt_left">female_literacy_rate_2011</td>
<td headers="estimate" class="gt_row gt_right">0.2321951</td>
<td headers="std.error" class="gt_row gt_right">0.03147744</td>
<td headers="statistic" class="gt_row gt_right">7.376557</td>
<td headers="p.value" class="gt_row gt_right">1.501286e-10</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
<p>&nbsp;</p>
<ul>
<li>Regression equation for our model (which we saw a looong time ago):</li>
</ul>
<div class="heq">
<p><span class="math display">\[\widehat{\text{life expectancy}} =  50.9 + 0.232\cdot\text{female literacy rate}\]</span></p>
</div>
</section>
<section id="how-do-we-interpret-the-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-interpret-the-coefficients">How do we interpret the coefficients?</h2>
<div class="heq">
<p><span class="math display">\[\widehat{\text{life expectancy}} =  50.9 + 0.232\cdot\text{female literacy rate}\]</span></p>
</div>
<ul>
<li><strong>Intercept</strong>
<ul>
<li>The expected outcome for the <span class="math inline">\(Y\)</span>-variable when the <span class="math inline">\(X\)</span>-variable is 0</li>
<li><strong>Example:</strong> The expected/average life expectancy is 50.9 years for a country with 0% female literacy.</li>
</ul></li>
<li><strong>Slope</strong>
<ul>
<li><p>For every increase of 1 unit in the <span class="math inline">\(X\)</span>-variable, there is an expected increase of, on average, <span class="math inline">\(\widehat\beta_1\)</span> units in the <span class="math inline">\(Y\)</span>-variable.</p></li>
<li><p>We only say that there is an expected increase and not necessarily a causal increase.</p></li>
<li><p><strong>Example:</strong> For every 1 percent increase in the female literacy rate, the expected/average life expectancy increases, on average, 0.232 years.</p></li>
</ul></li>
</ul>
</section>
<section id="next-time" class="level2">
<h2 class="anchored" data-anchor-id="next-time">Next time</h2>
<ul>
<li><p>Inference of our estimated coefficients</p></li>
<li><p>Inference of estimated expected <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span></p></li>
<li><p>Prediction</p></li>
<li><p>Hypothesis testing!</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>