---
title: "Key Info and Announcements"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements
- From a previous student My colleagues and I are conducting a focus group with masters of public health students to understand how students are currently engaging and utilizing resources at the OHSU-PSU School of Public Health. The focus group will happen on Saturday, February 15th at 11am-12:30 pm.  We would love to get more students involved from your program department to participate this upcoming Saturday and we would appreciate it if you could pass this opportunity along to your students. 
  - Interested students can sign up here and we will follow up students with next steps: <https://forms.gle/dpGj2XaqpBAEYihb9>
- No class on Monday!
- I added midterm feedback to HW 3: PLEASE DO THIS BY 2/14 (turn in with HW 3)
  - [Please complete the midterm feedback](https://forms.office.com/Pages/ResponsePage.aspx?id=V3lz4rj6fk2U9pvWr59xWFMopmPUjRtDiHLswhgacNhUQkdNUVRFQU41T0tRVDc0U1k2V0VFRVk4TS4u)

## Key Dates

- HW 3 due this Friday
- Midterm feedback due 2/14 with HW 3
- Lab 3 due 2/21
