---
title: "Lab 3"
author: "Your name here!!"
subtitle: "BSTA 512/612"
description: "Due: February 21, 2025 at 11pm"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
    self-contained: true
    number-sections: true
    number-depth: 4
---

```{r}
#| message: false

# PLEASE DO NOT REMOVE THIS CODE CHUNK!!!
### ADD YOUR LIBRARIES HERE!!! ####

library(tidyverse)
library(gtsummary)
library(here)
```

## Lab activities

Before starting this lab, you should go back to Lab 2, save a new `.rda` file that contains all the new variables from that Lab. Then you can load it here!

### Restate your research question

::: callout-important
##### Task

Please restate your research question below using the provided format. It's repetitive, but it helps me contextualize my feedback as I look through your lab.
:::

### Quality Control

::: callout-important
#### Tasks

1.  Filter out observations with a value of -999 in the race variable.
2.  Glimpse at the observations that may indicate a respondent who has not properly completed the survey portion. This will require filtering **for** specific answer choices. [Please see examples of `filter()` on it's documentation page.](https://dplyr.tidyverse.org/reference/filter.html#ref-examples)
:::

### Working with multi-selection variables

::: callout-important
#### Task

If you are using `genderIdentity` or `raceombmulti`, create indicator variables for each possible selection.
:::

### Thinking about potential confounders and effect modifiers

::: callout-important
##### Task

For each variable, consider how each could alter the relationship between IAT score and your variable of interest (from your research question). For each covariate, explain how it might or might not change the relationship.
:::

### Continuing data exploration

#### Bivariate exploration

::: callout-important
##### Task

For each variable outside of your research question, create the appropriate plot to visualize the relationship between IAT score and the variable. Comment if there is an obvious trend or not.
:::

#### Multivariate exploration

::: callout-important
##### Task

For at least 3 variables outside of your research question, create the appropriate plot to visualize the relationship between IAT score, your main variable (in research question), and the variable outside your research question. Comment whether you can determine anything from the plot or not. If you can, is there any indication that the variable is a confounder or effect modifier?
:::

### Fit a simple linear regression

::: callout-important
##### Task

Run a simple linear regression model for the relationship in your primary research question. Print the regression table. Interpret the results and comment on the initial trend you see.
:::

::: callout-important
##### Bonus Task

This is not required in Lab 3. However, if you want to run a multiple linear regression model with one other variable that you plotted in Multivariate Exploration, then you should try it! Do the results align with your ideas in Section 2.4 and/or the visualization you saw in Section 2.5?
:::
