---
title: "Key Info and Announcements"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- No class on Monday! MLKJ day!
- Everyone should be added to the OneDrive
- Exit ticket today will ask you about Thursday office hours 
- I will be working on muddy points from Lesson 2, 3, and 4 tonight or tomorrow!
  - I've been trying to paste the muddy points from last year so you at least have a reference
- Anything else?

## Key Dates

- Lab 1 due this Thursday at 11pm

## Additional Announcements from Student Success Center

### Check Out a Laptop and/or Noise Cancelling Headphones
 
Starting Winter Term, the Student Success Center is offering students the opportunity to check out in-person a laptop and/or a pair of noise cancelling headphones for up to 3 hours from the SSC Front desk VPT 620.

Alex, our new Administrative Coordinator, can help you with the checkout process! She is available in-person Monday through Friday from 8:30 am – 5:00 pm in VPT 620.

Please reach out to Alex Garfias Barajas if you have any questions: sphsuccess@ohsu.edu

 

### ATLAS TI and SAS
 
We have installed ATLAS TI and SAS on our Student Success Center desktops. Currently, only our desktops have SAS, and we are working on installing SAS to our laptops. Please let us know if there is any other software that would be beneficial to your academic success.

 
### Linguistic Equity Research Gathering. 

January 14th 11:30 am - 1:00 pm in Vanport 620M or Zoom. Lunch provided for those participating in person.

We hope to create a dedicated space for students to learn and engage with ongoing research on linguistic equity and health at the School of Public Health (SPH). Most importantly, the goal is to use this time to connect with one another, validate our collective knowledge, and share how we'd like to frame and shape SPH research that will directly impact our health and well-being (and those of future multilingual students!), de-centering English along the way. Please see the attached flyer for more information. Please RSVP here: https://portlandstate.qualtrics.com/jfe/form/SV_6StuUq6kI2JG5xA
NEXT WEEK! Talk by Dr. Mariana Chilton: The Painful Truth About Hunger in America. Wednesday, January 15th 3:00 pm – 5:00 pm in Vanport 515.
Join the SPH as they host the esteemed Dr. Mariana Chilton for an enlightening talk on "The Painful Truth About Hunger in America." With over 25 years of dedicated research, programming, and advocacy in the field, Dr. Chilton is a leading expert in addressing the systemic roots of hunger and poverty in the United States. Her book challenges conventional wisdom about hunger, highlighting that the issue extends beyond mere food scarcity to deeper, systemic socio-political issues. Drawing on interviews and extensive research, Dr. Chilton argues that to truly eradicate hunger, a holistic approach involving personal, political, and spiritual transformation is necessary.
This engaging talk will not only shed light on the hidden truths of food insecurity but also inspire actionable change. Don't miss this opportunity to gain profound insights from a pioneering voice in public health advocacy! This is a hybrid event and open to the community! If you need accommodations, email sphcomms@ohsu.edu.
 
### Manifesting Your Success hosted by SSC and TRIO-SSS. 

January 22nd 2:00 pm – 3:00 pm in Vanport 620M.
 
The Student Success Center and TRIO-SSS invite you to make vision boards to celebrate the new year and make your own yogurt parfait! Supplies will be provided!
 
Use this link to RSVP: https://forms.gle/QhAjkxtyHNe2x3X89
 
### Writing Resumes & Cover Letters for Public Health Opportunities. 

Friday, January 24th 12:00 pm – 1:00 pm via Zoom
 
Have you ever felt like you don't have the right experience to apply for a job, internship, or summer research program within Public Health? Join this resume and cover letter workshop to learn how to demonstrate that you meet qualifications while highlighting your experience, knowledge, and skillset for the opportunities you are applying for. We'll share the latest information on how to effectively write and format a resume and cover letter, and where to go for 1:1 support if needed. Please RSVP: https://portlandstate.joinhandshake.com/events/1679779/share_preview
 
### Careers in Public Health: Insights from Industry Professionals. 
Thursday, February 20th 12:00 – 1:00 pm. Virtual Event.
 
The Student Success Center and PSU’s Career Center are hosting a virtual panel featuring professionals from public service, health care, nonprofit education, and education. You’ll also learn insider tips and job search advice!
           
Please register for the event using Handshake: https://portlandstate.joinhandshake.com/events/1668028/share_preview
 
