{
  "hash": "89d5c06224569e983dfbf5d184555d16",
  "result": {
    "markdown": "---\ntitle: \"Lesson 12: Interactions, Part 2\"\nauthor: \"Nicky Wakim\"\ntitle-slide-attributes:\n    data-background-color: \"#213c96\"\ndate: \"02/19/2025\"\nformat: \n  revealjs:\n    theme: \"../simple_NW.scss\"\n    chalkboard: true\n    slide-number: true\n    show-slide-number: all\n    width: 1955\n    height: 1100\n    footer: \"Lesson 12: Interactions 2\"\n    highlight-style: ayu\n    html-math-method: mathjax\nexecute:\n  freeze: auto  # re-render only when source changes\n---\n\n\n\n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n::: lob\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n:::\n\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n\n## Do we think income level can be an effect modifier for world region?\n\n::: columns\n::: column\n-   Taking a break from female literacy rate to demonstrate interactions for two categorical variables\n\n-   We can start by visualizing the relationship between life expectancy and world region *by income level*\n\n-   Questions of interest: Does the effect of world region on life expectancy differ depending on income level?\n\n    -   This is the same as: Is income level an effect modifier for world region?\n\n-   Let's run an interaction model to see!\n:::\n\n::: column\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-2-1.png){fig-align='center' width=864}\n:::\n:::\n\n:::\n:::\n\n## Model with interaction between a *multi-level categorical and binary variables*\n\nModel we are fitting:\n\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{Americas}) + \\beta_3 I(\\text{Asia}) + \\beta_4 I(\\text{Europe}) + \\\\ & \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe})+ \\epsilon \\end{aligned}$$\n\n-   $LE$ as life expectancy\n-   $I(\\text{high income})$ as indicator of high income\n-   $I(\\text{Americas})$, $I(\\text{Asia})$, $I(\\text{Europe})$ as the indicator for each world region\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gapm_sub = gapm_sub %>% mutate(income_levels2 = relevel(income_levels2, ref = \"Higher income\")) # for poll everywhere\n\nm_int_wr_inc = lm(LifeExpectancyYrs ~ income_levels2 + four_regions +\n                  income_levels2*four_regions, data = gapm_sub)\nm_int_wr_inc = lm(LifeExpectancyYrs ~ income_levels2*four_regions, \n                data = gapm_sub)\n```\n:::\n\n\n## Displaying the regression table and writing fitted regression equation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(m_int_wr_inc, conf.int=T) %>% gt() %>% tab_options(table.font.size = 25) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"vdhhywxwmf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vdhhywxwmf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vdhhywxwmf thead, #vdhhywxwmf tbody, #vdhhywxwmf tfoot, #vdhhywxwmf tr, #vdhhywxwmf td, #vdhhywxwmf th {\n  border-style: none;\n}\n\n#vdhhywxwmf p {\n  margin: 0;\n  padding: 0;\n}\n\n#vdhhywxwmf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 25px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vdhhywxwmf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vdhhywxwmf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vdhhywxwmf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vdhhywxwmf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vdhhywxwmf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vdhhywxwmf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vdhhywxwmf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vdhhywxwmf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vdhhywxwmf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vdhhywxwmf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vdhhywxwmf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vdhhywxwmf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vdhhywxwmf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vdhhywxwmf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vdhhywxwmf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vdhhywxwmf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vdhhywxwmf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vdhhywxwmf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vdhhywxwmf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vdhhywxwmf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vdhhywxwmf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vdhhywxwmf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vdhhywxwmf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vdhhywxwmf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vdhhywxwmf .gt_left {\n  text-align: left;\n}\n\n#vdhhywxwmf .gt_center {\n  text-align: center;\n}\n\n#vdhhywxwmf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vdhhywxwmf .gt_font_normal {\n  font-weight: normal;\n}\n\n#vdhhywxwmf .gt_font_bold {\n  font-weight: bold;\n}\n\n#vdhhywxwmf .gt_font_italic {\n  font-style: italic;\n}\n\n#vdhhywxwmf .gt_super {\n  font-size: 65%;\n}\n\n#vdhhywxwmf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vdhhywxwmf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vdhhywxwmf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vdhhywxwmf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vdhhywxwmf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vdhhywxwmf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vdhhywxwmf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#vdhhywxwmf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#vdhhywxwmf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">60.850</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.281</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">47.488</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">58.290</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">63.410</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_levels2Higher income</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">2.100</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.865</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.733</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.466</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−3.624</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">7.824</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsAmericas</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">10.800</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">3.844</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">2.810</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.007</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">3.121</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">18.479</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsAsia</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">7.467</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">1.957</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.815</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">3.556</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">11.377</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">four_regionsEurope</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">11.500</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.865</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.014</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">5.776</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">17.224</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_levels2Higher income:four_regionsAmericas</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">2.640</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.896</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.539</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.592</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−7.141</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">12.421</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_levels2Higher income:four_regionsAsia</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">1.543</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">3.956</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.390</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.698</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−6.360</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">9.447</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">income_levels2Higher income:four_regionsEurope</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">2.382</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">4.020</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.592</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.556</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−5.649</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">10.412</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\widehat\\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = & 60.85 + 2.10 \\cdot I(\\text{high income}) + 10.8 \\cdot I(\\text{Americas}) + 7.47\\cdot  I(\\text{Asia}) + 11.50 \\cdot I(\\text{Europe}) + \\\\ & 2.64 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + 1.54 \\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & 2.38 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\end{aligned}$$\n\n## Poll Everywhere Question 4\n\n::: columns\n::: {.column width=\"60%\"}\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=768}\n:::\n:::\n\n:::\n:::\n\n\n## Comparing fitted regression *means* for each world region {.smaller}\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\widehat\\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = & 60.85 + 2.10 \\cdot I(\\text{high income}) + 10.8 \\cdot I(\\text{Americas}) + 7.47\\cdot  I(\\text{Asia}) + 11.50 \\cdot I(\\text{Europe}) + \\\\ & 2.64 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + 1.54 \\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & 2.38 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\end{aligned}$$\n\n::: columns\n::: {.column width=\"25%\"}\n::: proof1\n::: proof-title\nAfrica\n:::\n\n::: proof-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ & \\widehat\\beta_2 \\cdot 0 + \\widehat\\beta_3 \\cdot 0 + \\widehat\\beta_4 \\cdot 0 + \\\\ & \\widehat\\beta_5 I(\\text{high income}) \\cdot 0 + \\\\ & \\widehat\\beta_6 I(\\text{high income}) \\cdot 0+ \\\\& \\widehat\\beta_7 I(\\text{high income}) \\cdot 0 \\\\\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income})\\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"25%\"}\n::: fact\n::: fact-title\nThe Americas\n:::\n\n::: fact-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ & \\widehat\\beta_2 \\cdot 1 + \\widehat\\beta_3 \\cdot 0 + \\widehat\\beta_4 \\cdot 0 + \\\\ &  \\widehat\\beta_5 I(\\text{high income}) \\cdot 1 + \\\\ & \\widehat\\beta_6 I(\\text{high income}) \\cdot 0+ \\\\ & \\widehat\\beta_7 I(\\text{high income}) \\cdot 0 \\\\\n\\widehat{LE} = &\\big(\\widehat\\beta_0+\\widehat\\beta_2\\big) + \\\\ &\\big(\\widehat\\beta_1 + \\widehat\\beta_5\\big)I(\\text{high income}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"25%\"}\n::: proposition\n::: prop-title\nAsia\n:::\n\n::: prop-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ & \\widehat\\beta_2 \\cdot 0 + \\widehat\\beta_3 \\cdot 1 + \\widehat\\beta_4 \\cdot 0 + \\\\ & \\widehat\\beta_5 I(\\text{high income}) \\cdot 0 + \\\\ & \\widehat\\beta_6 I(\\text{high income}) \\cdot 1+ \\\\ & \\widehat\\beta_7 I(\\text{high income}) \\cdot 0 \\\\\n\\widehat{LE} = &\\big(\\widehat\\beta_0+\\widehat\\beta_3\\big) + \\\\ &\\big(\\widehat\\beta_1 + \\widehat\\beta_6\\big)I(\\text{high income}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"25%\"}\n::: definition\n::: def-title\nEurope\n:::\n\n::: def-cont\n$$\\begin{aligned} \n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\\\ & \\widehat\\beta_2 \\cdot 0 + \\widehat\\beta_3 \\cdot 0 + \\widehat\\beta_4 \\cdot 1 + \\\\ & \\widehat\\beta_5 I(\\text{high income}) \\cdot 0 + \\\\ & \\widehat\\beta_6 I(\\text{high income}) \\cdot 0+ \\\\ & \\widehat\\beta_7 I(\\text{high income}) \\cdot 1 \\\\\n\\widehat{LE} = &\\big(\\widehat\\beta_0+\\widehat\\beta_4\\big) + \\\\ & \\big(\\widehat\\beta_1 + \\widehat\\beta_7\\big)I(\\text{high income}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Comparing fitted regression *means* for each income level {.smaller}\n\n$$\\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 I(\\text{high income}) + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\widehat\\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = & 60.85 + 2.10 \\cdot I(\\text{high income}) + 10.8 \\cdot I(\\text{Americas}) + 7.47\\cdot  I(\\text{Asia}) + 11.50 \\cdot I(\\text{Europe}) + \\\\ & 2.64 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + 1.54 \\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & 2.38 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\end{aligned}$$\n\n::: columns\n::: column\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income}) =0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 0 + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot 0\\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot 0 \\cdot I(\\text{Asia})+ \\widehat\\beta_7 \\cdot 0\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: column\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot 1 + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot 1\\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot 1 \\cdot I(\\text{Asia})+ \\widehat\\beta_7 \\cdot 1\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = & (\\widehat\\beta_0 + \\widehat\\beta_1)  + (\\widehat\\beta_2 + \\widehat\\beta_5) I(\\text{Americas}) + (\\widehat\\beta_3 + \\widehat\\beta_6)  I(\\text{Asia}) + \\\\ & (\\widehat\\beta_4 + \\widehat\\beta_7)  I(\\text{Europe}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n- Example interpretation: The America's effect on mean life expectancy increases $\\widehat{\\beta}_5$ comparing high income to low income countries.\n\n## Let's take a look back at the plot\n\n::: columns\n::: {.column width=\"50%\"}\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income}) =0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\\\ & \\widehat\\beta_4 I(\\text{Europe}) \\\\\n\\end{aligned}$$\n:::\n:::\n\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & (\\widehat\\beta_0 + \\widehat\\beta_1)  + (\\widehat\\beta_2 + \\widehat\\beta_5) I(\\text{Americas}) + \\\\& (\\widehat\\beta_3 + \\widehat\\beta_6)  I(\\text{Asia}) +  (\\widehat\\beta_4 + \\widehat\\beta_7)  I(\\text{Europe}) \\\\\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12_Interactions_02_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=816}\n:::\n:::\n\n:::\n:::\n\n## Interpretation for interaction between two categorical variables\n\n$$ \\begin{aligned}\n\\widehat{LE} = &\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{high income}) + \\widehat\\beta_2 I(\\text{Americas}) + \\widehat\\beta_3 I(\\text{Asia}) + \\widehat\\beta_4 I(\\text{Europe}) + \\\\ & \\widehat\\beta_5 \\cdot I(\\text{high income})\\cdot I(\\text{Americas}) + \\widehat\\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\widehat\\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe}) \\\\\n\\widehat{LE} = & \\bigg[\\widehat\\beta_0 + \\widehat\\beta_1 \\cdot I(\\text{high income})\\bigg]  + \\bigg[\\widehat\\beta_2 + \\widehat\\beta_5 \\cdot I(\\text{high income})\\bigg] I(\\text{Americas}) + \\\\ & \\bigg[\\widehat\\beta_3 + \\widehat\\beta_6 \\cdot I(\\text{high income})\\bigg]  I(\\text{Asia}) +  \\bigg[\\widehat\\beta_4 + \\widehat\\beta_7 \\cdot I(\\text{high income})\\bigg]  I(\\text{Europe}) \\\\\n\\end{aligned}$$\n\n-   Interpretation:\n    -   $\\beta_1$ = mean change in the Africa's life expectancy, comparing high income to low income countries\n    -   $\\beta_5$ = mean change in the Americas' effect, comparing high income to low income countries\n    -   $\\beta_6$ = mean change in Asia's effect, comparing high income to low income countries\n    -   $\\beta_7$ = mean change in Europe's effect, comparing high income to low income countries\n\n## Test interaction between two categorical variables (1/2) {.smaller}\n\n-   We run an F-test for a group of coefficients ($\\beta_5$, $\\beta_6$, $\\beta_7$) in the below model (see lesson 9)\n\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{Americas}) + \\beta_3 I(\\text{Asia}) + \\beta_4 I(\\text{Europe}) + \\\\ & \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\\\ & \\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe})+ \\epsilon \\end{aligned}$$\n\n::: columns\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$\\beta_5= \\beta_6 = \\beta_7 =0$\n:::\n:::\n:::\n\n::: {.column width=\"55%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$\\beta_5\\neq0$ and/or $\\beta_6\\neq0$ and/or $\\beta_7\\neq0$\n:::\n:::\n:::\n:::\n\n::: columns\n::: {.column width=\"45%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{Americas}) + \\\\& \\beta_3 I(\\text{Asia}) + \\beta_4 I(\\text{Europe}) + \\epsilon \\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"55%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$$\\begin{aligned}LE = &\\beta_0 + \\beta_1 I(\\text{high income}) + \\beta_2 I(\\text{Americas}) + \\beta_3 I(\\text{Asia}) + \\\\ & \\beta_4 I(\\text{Europe}) + \\beta_5 \\cdot I(\\text{high income}) \\cdot I(\\text{Americas}) + \\\\ & \\beta_6\\cdot I(\\text{high income}) \\cdot I(\\text{Asia})+ \\beta_7 \\cdot I(\\text{high income})\\cdot I(\\text{Europe})+ \\epsilon \\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Test interaction between two categorical variables (2/2)\n\n-   Fit the reduced and full model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_wr_inc_red = lm(LifeExpectancyYrs ~ income_levels2 + four_regions, \n                   data = gapm_sub)\nm_int_wr_inc_full = lm(LifeExpectancyYrs ~ income_levels2 + four_regions +\n                          income_levels2*four_regions, data = gapm_sub)\n```\n:::\n\n\n-   Display the ANOVA table with F-statistic and p-value\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"qbpxyiejqo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qbpxyiejqo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qbpxyiejqo thead, #qbpxyiejqo tbody, #qbpxyiejqo tfoot, #qbpxyiejqo tr, #qbpxyiejqo td, #qbpxyiejqo th {\n  border-style: none;\n}\n\n#qbpxyiejqo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qbpxyiejqo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qbpxyiejqo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qbpxyiejqo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qbpxyiejqo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qbpxyiejqo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qbpxyiejqo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qbpxyiejqo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qbpxyiejqo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qbpxyiejqo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qbpxyiejqo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qbpxyiejqo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qbpxyiejqo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qbpxyiejqo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qbpxyiejqo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qbpxyiejqo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbpxyiejqo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qbpxyiejqo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qbpxyiejqo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qbpxyiejqo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbpxyiejqo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qbpxyiejqo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbpxyiejqo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qbpxyiejqo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbpxyiejqo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qbpxyiejqo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbpxyiejqo .gt_left {\n  text-align: left;\n}\n\n#qbpxyiejqo .gt_center {\n  text-align: center;\n}\n\n#qbpxyiejqo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qbpxyiejqo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qbpxyiejqo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qbpxyiejqo .gt_font_italic {\n  font-style: italic;\n}\n\n#qbpxyiejqo .gt_super {\n  font-size: 65%;\n}\n\n#qbpxyiejqo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qbpxyiejqo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qbpxyiejqo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qbpxyiejqo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qbpxyiejqo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qbpxyiejqo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qbpxyiejqo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qbpxyiejqo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qbpxyiejqo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ income_levels2 + four_regions</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">67.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">1,693.242</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ income_levels2 + four_regions + income_levels2 * four_regions</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">64.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">1,681.304</td>\n<td headers=\"df\" class=\"gt_row gt_right\">3.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">11.938</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.151</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.928</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n-   Conclusion: There is not a significant interaction between world region and income level (p = 0.928).\n\n# Learning Objectives\n\n**Last time:**\n\n1.  Define confounders and effect modifiers, and how they interact with the main relationship we model.\n2.  Interpret the interaction component of a model with **a binary categorical covariate and continuous covariate**, and how the main variable's effect changes.\n3.  Interpret the interaction component of a model with **a multi-level categorical covariate and continuous covariate**, and how the main variable's effect changes.\n\n**This time:**\n\n4.  Interpret the interaction component of a model with **two categorical covariates**, and how the main variable's effect changes.\n\n::: lob\n5.  Interpret the interaction component of a model with **two continuous covariates**, and how the main variable's effect changes.\n:::\n\n## Do we think food supply is an effect modifier for female literacy rate?\n\n::: columns\n::: {.column width=\"40%\"}\n-   We can start by visualizing the relationship between life expectancy and female literacy rate *by food supply*\n\n-   Questions of interest: Does the effect of female literacy rate on life expectancy differ depending on food supply?\n\n    -   This is the same as: Is food supply is an effect modifier for female literacy rate? Is food supply an effect modifier of the association between life expectancy and female literacy rate?\n\n-   Let's run an interaction model to see!\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n```{=html}\n<div class=\"girafe html-widget html-fill-item\" id=\"htmlwidget-a4639f93b65ce6c258b2\" style=\"width:576px;height:384px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-a4639f93b65ce6c258b2\">{\"x\":{\"html\":\"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' class='ggiraph-svg' role='graphics-document' id='svg_19208998_de5f_480d_825f_587a3564c064' viewBox='0 0 432 288'>\\n <defs id='svg_19208998_de5f_480d_825f_587a3564c064_defs'>\\n  <clipPath id='svg_19208998_de5f_480d_825f_587a3564c064_c1'>\\n   <rect x='0' y='0' width='432' height='288'/>\\n  <\\/clipPath>\\n  <clipPath id='svg_19208998_de5f_480d_825f_587a3564c064_c2'>\\n   <rect x='33.27' y='5.48' width='279' height='250.79'/>\\n  <\\/clipPath>\\n <\\/defs>\\n <g id='svg_19208998_de5f_480d_825f_587a3564c064_rootg' class='ggiraph-svg-rootg'>\\n  <g clip-path='url(#svg_19208998_de5f_480d_825f_587a3564c064_c1)'>\\n   <rect x='0' y='0' width='432' height='288' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.75' stroke-linejoin='round' stroke-linecap='round' class='ggiraph-svg-bg'/>\\n   <rect x='0' y='0' width='432' height='288' fill='#FFFFFF' fill-opacity='1' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='round'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_19208998_de5f_480d_825f_587a3564c064_c2)'>\\n   <rect x='33.27' y='5.48' width='279' height='250.79' fill='#EBEBEB' fill-opacity='1' stroke='none'/>\\n   <polyline points='33.27,199.39 312.27,199.39' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,134.42 312.27,134.42' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,69.45 312.27,69.45' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='52.99,256.27 52.99,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='123.45,256.27 123.45,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='193.91,256.27 193.91,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='264.36,256.27 264.36,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.53' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,231.87 312.27,231.87' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,166.90 312.27,166.90' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,101.94 312.27,101.94' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='33.27,36.97 312.27,36.97' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='88.22,256.27 88.22,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='158.68,256.27 158.68,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='229.13,256.27 229.13,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='299.59,256.27 299.59,5.48' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e1' cx='54.4' cy='188.34' r='1.47pt' fill='#16314C' fill-opacity='1' stroke='#16314C' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='1' title='1&amp;lt;br/&amp;gt;FemaleLiteracyRate=13&amp;lt;br/&amp;gt;LifeExpectancyYrs=56.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e2' cx='287.47' cy='58.41' r='1.47pt' fill='#3773A4' fill-opacity='1' stroke='#3773A4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='2' title='2&amp;lt;br/&amp;gt;FemaleLiteracyRate=95.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e3' cx='182.91' cy='161.06' r='1.47pt' fill='#204464' fill-opacity='1' stroke='#204464' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='3' title='3&amp;lt;br/&amp;gt;FemaleLiteracyRate=58.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=60.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e4' cx='297.9' cy='57.11' r='1.47pt' fill='#1E4161' fill-opacity='1' stroke='#1E4161' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='4' title='4&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.4&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e5' cx='293.67' cy='62.95' r='1.47pt' fill='#3875A7' fill-opacity='1' stroke='#3875A7' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='5' title='5&amp;lt;br/&amp;gt;FemaleLiteracyRate=97.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=76'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e6' cx='298.18' cy='77.25' r='1.47pt' fill='#2C5C85' fill-opacity='1' stroke='#2C5C85' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='6' title='6&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e7' cx='168.26' cy='95.44' r='1.47pt' fill='#204566' fill-opacity='1' stroke='#204566' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='7' title='7&amp;lt;br/&amp;gt;FemaleLiteracyRate=53.4&amp;lt;br/&amp;gt;LifeExpectancyYrs=71'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e8' cx='290.29' cy='57.11' r='1.47pt' fill='#3773A4' fill-opacity='1' stroke='#3773A4' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='8' title='8&amp;lt;br/&amp;gt;FemaleLiteracyRate=96.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e9' cx='259.01' cy='174.05' r='1.47pt' fill='#1B3B59' fill-opacity='1' stroke='#1B3B59' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='9' title='9&amp;lt;br/&amp;gt;FemaleLiteracyRate=85.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=58.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e10' cx='282.4' cy='56.46' r='1.47pt' fill='#316693' fill-opacity='1' stroke='#316693' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='10' title='10&amp;lt;br/&amp;gt;FemaleLiteracyRate=93.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=77'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e11' cx='293.95' cy='74' r='1.47pt' fill='#2B5B83' fill-opacity='1' stroke='#2B5B83' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='11' title='11&amp;lt;br/&amp;gt;FemaleLiteracyRate=98&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.3'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e12' cx='244.07' cy='84.39' r='1.47pt' fill='#254E72' fill-opacity='1' stroke='#254E72' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='12' title='12&amp;lt;br/&amp;gt;FemaleLiteracyRate=80.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=72.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e13' cx='142.33' cy='244.87' r='1.47pt' fill='#18344F' fill-opacity='1' stroke='#18344F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='13' title='13&amp;lt;br/&amp;gt;FemaleLiteracyRate=44.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=48'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e14' cx='89.35' cy='186.4' r='1.47pt' fill='#152F48' fill-opacity='1' stroke='#152F48' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='14' title='14&amp;lt;br/&amp;gt;FemaleLiteracyRate=25.4&amp;lt;br/&amp;gt;LifeExpectancyYrs=57'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e15' cx='281.83' cy='56.46' r='1.47pt' fill='#29567D' fill-opacity='1' stroke='#29567D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='15' title='15&amp;lt;br/&amp;gt;FemaleLiteracyRate=93.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=77'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e16' cx='289.72' cy='33.72' r='1.47pt' fill='#2F628D' fill-opacity='1' stroke='#2F628D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='16' title='16&amp;lt;br/&amp;gt;FemaleLiteracyRate=96.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=80.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e17' cx='151.91' cy='187.04' r='1.47pt' fill='#2B5B84' fill-opacity='1' stroke='#2B5B84' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='17' title='17&amp;lt;br/&amp;gt;FemaleLiteracyRate=47.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=56.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e18' cx='294.8' cy='59.06' r='1.47pt' fill='#336A98' fill-opacity='1' stroke='#336A98' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='18' title='18&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e19' cx='299.02' cy='46.71' r='1.47pt' fill='#3D7EB3' fill-opacity='1' stroke='#3D7EB3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='19' title='19&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.8&amp;lt;br/&amp;gt;LifeExpectancyYrs=78.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e20' cx='294.23' cy='35.67' r='1.47pt' fill='#28557B' fill-opacity='1' stroke='#28557B' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='20' title='20&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.1&amp;lt;br/&amp;gt;LifeExpectancyYrs=80.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e21' cx='271.97' cy='71.4' r='1.47pt' fill='#244D71' fill-opacity='1' stroke='#244D71' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='21' title='21&amp;lt;br/&amp;gt;FemaleLiteracyRate=90.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e22' cx='271.97' cy='56.46' r='1.47pt' fill='#1F4262' fill-opacity='1' stroke='#1F4262' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='22' title='22&amp;lt;br/&amp;gt;FemaleLiteracyRate=90.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=77'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e23' cx='199.82' cy='96.09' r='1.47pt' fill='#4690CB' fill-opacity='1' stroke='#4690CB' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='23' title='23&amp;lt;br/&amp;gt;FemaleLiteracyRate=64.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=70.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e24' cx='299.02' cy='61.01' r='1.47pt' fill='#3D7EB3' fill-opacity='1' stroke='#3D7EB3' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='24' title='24&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.8&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.3'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e25' cx='259.01' cy='145.46' r='1.47pt' fill='#2B5B83' fill-opacity='1' stroke='#2B5B83' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='25' title='25&amp;lt;br/&amp;gt;FemaleLiteracyRate=85.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=63.3'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e26' cx='135.85' cy='127.92' r='1.47pt' fill='#29567C' fill-opacity='1' stroke='#29567C' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='26' title='26&amp;lt;br/&amp;gt;FemaleLiteracyRate=41.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=66'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e27' cx='298.74' cy='82.45' r='1.47pt' fill='#2C5D87' fill-opacity='1' stroke='#2C5D87' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='27' title='27&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=73'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e28' cx='289.16' cy='33.72' r='1.47pt' fill='#4288C0' fill-opacity='1' stroke='#4288C0' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='28' title='28&amp;lt;br/&amp;gt;FemaleLiteracyRate=96.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=80.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e29' cx='218.14' cy='92.19' r='1.47pt' fill='#22496B' fill-opacity='1' stroke='#22496B' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='29' title='29&amp;lt;br/&amp;gt;FemaleLiteracyRate=71.1&amp;lt;br/&amp;gt;LifeExpectancyYrs=71.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e30' cx='136.41' cy='191.59' r='1.47pt' fill='#1D3F5F' fill-opacity='1' stroke='#1D3F5F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='30' title='30&amp;lt;br/&amp;gt;FemaleLiteracyRate=42.1&amp;lt;br/&amp;gt;LifeExpectancyYrs=56.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e31' cx='257.03' cy='90.24' r='1.47pt' fill='#265176' fill-opacity='1' stroke='#265176' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='31' title='31&amp;lt;br/&amp;gt;FemaleLiteracyRate=84.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=71.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e32' cx='296.49' cy='70.1' r='1.47pt' fill='#356E9D' fill-opacity='1' stroke='#356E9D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='32' title='32&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e33' cx='271.69' cy='100.64' r='1.47pt' fill='#29577E' fill-opacity='1' stroke='#29577E' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='33' title='33&amp;lt;br/&amp;gt;FemaleLiteracyRate=90.1&amp;lt;br/&amp;gt;LifeExpectancyYrs=70.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e34' cx='218.42' cy='117.53' r='1.47pt' fill='#22496B' fill-opacity='1' stroke='#22496B' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='34' title='34&amp;lt;br/&amp;gt;FemaleLiteracyRate=71.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=67.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e35' cx='295.92' cy='25.27' r='1.47pt' fill='#4792CE' fill-opacity='1' stroke='#4792CE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='35' title='35&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=81.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e36' cx='276.48' cy='70.75' r='1.47pt' fill='#2B5B83' fill-opacity='1' stroke='#2B5B83' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='36' title='36&amp;lt;br/&amp;gt;FemaleLiteracyRate=91.8&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e37' cx='282.4' cy='62.31' r='1.47pt' fill='#3874A5' fill-opacity='1' stroke='#3874A5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='37' title='37&amp;lt;br/&amp;gt;FemaleLiteracyRate=93.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.1'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e38' cx='299.02' cy='78.55' r='1.47pt' fill='#3874A6' fill-opacity='1' stroke='#3874A6' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='38' title='38&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.8&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e39' cx='298.74' cy='79.2' r='1.47pt' fill='#4186BE' fill-opacity='1' stroke='#4186BE' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='39' title='39&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e40' cx='288.32' cy='74.65' r='1.47pt' fill='#306490' fill-opacity='1' stroke='#306490' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='40' title='40&amp;lt;br/&amp;gt;FemaleLiteracyRate=96&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e41' cx='87.1' cy='166.9' r='1.47pt' fill='#2D5F89' fill-opacity='1' stroke='#2D5F89' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='41' title='41&amp;lt;br/&amp;gt;FemaleLiteracyRate=24.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=60'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e42' cx='164.31' cy='111.03' r='1.47pt' fill='#2C5D87' fill-opacity='1' stroke='#2C5D87' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='42' title='42&amp;lt;br/&amp;gt;FemaleLiteracyRate=52&amp;lt;br/&amp;gt;LifeExpectancyYrs=68.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e43' cx='262.11' cy='77.25' r='1.47pt' fill='#356E9D' fill-opacity='1' stroke='#356E9D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='43' title='43&amp;lt;br/&amp;gt;FemaleLiteracyRate=86.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e44' cx='277.89' cy='64.25' r='1.47pt' fill='#346C9B' fill-opacity='1' stroke='#346C9B' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='44' title='44&amp;lt;br/&amp;gt;FemaleLiteracyRate=92.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=75.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e45' cx='295.36' cy='92.19' r='1.47pt' fill='#29567D' fill-opacity='1' stroke='#29567D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='45' title='45&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=71.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e46' cx='293.67' cy='124.03' r='1.47pt' fill='#214668' fill-opacity='1' stroke='#214668' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='46' title='46&amp;lt;br/&amp;gt;FemaleLiteracyRate=97.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=66.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e47' cx='292.82' cy='60.36' r='1.47pt' fill='#438BC5' fill-opacity='1' stroke='#438BC5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='47' title='47&amp;lt;br/&amp;gt;FemaleLiteracyRate=97.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.4'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e48' cx='180.1' cy='77.25' r='1.47pt' fill='#3F82B8' fill-opacity='1' stroke='#3F82B8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='48' title='48&amp;lt;br/&amp;gt;FemaleLiteracyRate=57.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e49' cx='272.53' cy='118.83' r='1.47pt' fill='#234B6F' fill-opacity='1' stroke='#234B6F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='49' title='49&amp;lt;br/&amp;gt;FemaleLiteracyRate=90.4&amp;lt;br/&amp;gt;LifeExpectancyYrs=67.4'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e50' cx='149.38' cy='110.38' r='1.47pt' fill='#265075' fill-opacity='1' stroke='#265075' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='50' title='50&amp;lt;br/&amp;gt;FemaleLiteracyRate=46.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=68.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e51' cx='298.46' cy='59.71' r='1.47pt' fill='#4289C1' fill-opacity='1' stroke='#4289C1' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='51' title='51&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=76.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e52' cx='282.68' cy='36.32' r='1.47pt' fill='#438BC5' fill-opacity='1' stroke='#438BC5' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='52' title='52&amp;lt;br/&amp;gt;FemaleLiteracyRate=94&amp;lt;br/&amp;gt;LifeExpectancyYrs=80.1'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e53' cx='291.7' cy='72.7' r='1.47pt' fill='#3E81B7' fill-opacity='1' stroke='#3E81B7' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='53' title='53&amp;lt;br/&amp;gt;FemaleLiteracyRate=97.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e54' cx='295.64' cy='92.19' r='1.47pt' fill='#2F628D' fill-opacity='1' stroke='#2F628D' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='54' title='54&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=71.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e55' cx='249.42' cy='67.5' r='1.47pt' fill='#3671A1' fill-opacity='1' stroke='#3671A1' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='55' title='55&amp;lt;br/&amp;gt;FemaleLiteracyRate=82.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=75.3'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e56' cx='290.85' cy='70.75' r='1.47pt' fill='#2A5880' fill-opacity='1' stroke='#2A5880' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='56' title='56&amp;lt;br/&amp;gt;FemaleLiteracyRate=96.9&amp;lt;br/&amp;gt;LifeExpectancyYrs=74.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e57' cx='109.64' cy='194.84' r='1.47pt' fill='#1D3F5F' fill-opacity='1' stroke='#1D3F5F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='57' title='57&amp;lt;br/&amp;gt;FemaleLiteracyRate=32.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=55.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e58' cx='298.74' cy='38.27' r='1.47pt' fill='#3976A7' fill-opacity='1' stroke='#3976A7' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='58' title='58&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=79.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e59' cx='277.61' cy='194.19' r='1.47pt' fill='#336A98' fill-opacity='1' stroke='#336A98' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='59' title='59&amp;lt;br/&amp;gt;FemaleLiteracyRate=92.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=55.8'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e60' cx='195.88' cy='124.67' r='1.47pt' fill='#1E405F' fill-opacity='1' stroke='#1E405F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='60' title='60&amp;lt;br/&amp;gt;FemaleLiteracyRate=63.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=66.5'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e61' cx='263.8' cy='239.02' r='1.47pt' fill='#1B3C5A' fill-opacity='1' stroke='#1B3C5A' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='61' title='61&amp;lt;br/&amp;gt;FemaleLiteracyRate=87.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=48.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e62' cx='298.46' cy='102.59' r='1.47pt' fill='#142E47' fill-opacity='1' stroke='#142E47' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='62' title='62&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.6&amp;lt;br/&amp;gt;LifeExpectancyYrs=69.9'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e63' cx='153.04' cy='169.5' r='1.47pt' fill='#1F4262' fill-opacity='1' stroke='#1F4262' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='63' title='63&amp;lt;br/&amp;gt;FemaleLiteracyRate=48&amp;lt;br/&amp;gt;LifeExpectancyYrs=59.6'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e64' cx='295.36' cy='84.39' r='1.47pt' fill='#306490' fill-opacity='1' stroke='#306490' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='64' title='64&amp;lt;br/&amp;gt;FemaleLiteracyRate=98.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=72.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e65' cx='272.25' cy='48.66' r='1.47pt' fill='#4A99D7' fill-opacity='1' stroke='#4A99D7' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='65' title='65&amp;lt;br/&amp;gt;FemaleLiteracyRate=90.3&amp;lt;br/&amp;gt;LifeExpectancyYrs=78.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e66' cx='298.18' cy='112.33' r='1.47pt' fill='#2E608A' fill-opacity='1' stroke='#2E608A' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='66' title='66&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=68.4'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e67' cx='298.74' cy='94.79' r='1.47pt' fill='#3976A8' fill-opacity='1' stroke='#3976A8' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='67' title='67&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.7&amp;lt;br/&amp;gt;LifeExpectancyYrs=71.1'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e68' cx='297.33' cy='108.43' r='1.47pt' fill='#29567C' fill-opacity='1' stroke='#29567C' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='68' title='68&amp;lt;br/&amp;gt;FemaleLiteracyRate=99.2&amp;lt;br/&amp;gt;LifeExpectancyYrs=69'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e69' cx='247.45' cy='146.11' r='1.47pt' fill='#2D5F8A' fill-opacity='1' stroke='#2D5F8A' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='69' title='69&amp;lt;br/&amp;gt;FemaleLiteracyRate=81.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=63.2'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e70' cx='275.35' cy='80.5' r='1.47pt' fill='#29587F' fill-opacity='1' stroke='#29587F' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='70' title='70&amp;lt;br/&amp;gt;FemaleLiteracyRate=91.4&amp;lt;br/&amp;gt;LifeExpectancyYrs=73.3'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e71' cx='154.45' cy='116.88' r='1.47pt' fill='#193754' fill-opacity='1' stroke='#193754' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='71' title='71&amp;lt;br/&amp;gt;FemaleLiteracyRate=48.5&amp;lt;br/&amp;gt;LifeExpectancyYrs=67.7'/>\\n   <circle id='svg_19208998_de5f_480d_825f_587a3564c064_e72' cx='243.51' cy='219.53' r='1.47pt' fill='#193753' fill-opacity='1' stroke='#193753' stroke-opacity='1' stroke-width='0.71' stroke-linejoin='round' stroke-linecap='round' data-id='72' title='72&amp;lt;br/&amp;gt;FemaleLiteracyRate=80.1&amp;lt;br/&amp;gt;LifeExpectancyYrs=51.9'/>\\n   <polyline id='svg_19208998_de5f_480d_825f_587a3564c064_e73' points='45.95,219.34 60.04,214.16 74.13,208.97 88.22,203.78 102.31,198.60 116.40,193.41 130.50,188.23 144.59,183.04 158.68,177.85 172.77,172.67 186.86,167.48 200.95,162.30 215.04,157.11 229.13,151.93 243.22,146.74 257.31,141.55 271.41,136.37 285.50,131.18 299.59,126.00' fill='none' stroke='#132B43' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for FoodSupplykcPPD=2000&amp;lt;br/&amp;gt;y = 0.16*x +50.33' data-id='1'/>\\n   <polyline id='svg_19208998_de5f_480d_825f_587a3564c064_e74' points='45.95,190.50 60.04,185.40 74.13,180.31 88.22,175.21 102.31,170.11 116.40,165.01 130.50,159.91 144.59,154.81 158.68,149.71 172.77,144.61 186.86,139.51 200.95,134.41 215.04,129.31 229.13,124.21 243.22,119.11 257.31,114.02 271.41,108.92 285.50,103.82 299.59,98.72' fill='none' stroke='#22496C' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for FoodSupplykcPPD=2500&amp;lt;br/&amp;gt;y = 0.16*x +54.8' data-id='21'/>\\n   <polyline id='svg_19208998_de5f_480d_825f_587a3564c064_e75' points='45.95,161.67 60.04,156.65 74.13,151.64 88.22,146.63 102.31,141.62 116.40,136.60 130.50,131.59 144.59,126.58 158.68,121.56 172.77,116.55 186.86,111.54 200.95,106.53 215.04,101.51 229.13,96.50 243.22,91.49 257.31,86.48 271.41,81.46 285.50,76.45 299.59,71.44' fill='none' stroke='#336A98' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for FoodSupplykcPPD=3000&amp;lt;br/&amp;gt;y = 0.15*x +59.26' data-id='41'/>\\n   <polyline id='svg_19208998_de5f_480d_825f_587a3564c064_e76' points='45.95,132.83 60.04,127.90 74.13,122.98 88.22,118.05 102.31,113.12 116.40,108.20 130.50,103.27 144.59,98.35 158.68,93.42 172.77,88.49 186.86,83.57 200.95,78.64 215.04,73.72 229.13,68.79 243.22,63.86 257.31,58.94 271.41,54.01 285.50,49.08 299.59,44.16' fill='none' stroke='#448DC6' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for FoodSupplykcPPD=3500&amp;lt;br/&amp;gt;y = 0.15*x +63.73' data-id='61'/>\\n   <polyline id='svg_19208998_de5f_480d_825f_587a3564c064_e77' points='45.95,103.99 60.04,99.15 74.13,94.31 88.22,89.47 102.31,84.63 116.40,79.79 130.50,74.95 144.59,70.11 158.68,65.28 172.77,60.44 186.86,55.60 200.95,50.76 215.04,45.92 229.13,41.08 243.22,36.24 257.31,31.40 271.41,26.56 285.50,21.72 299.59,16.88' fill='none' stroke='#56B1F7' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt' title='for FoodSupplykcPPD=4000&amp;lt;br/&amp;gt;y = 0.15*x +68.19' data-id='81'/>\\n  <\\/g>\\n  <g clip-path='url(#svg_19208998_de5f_480d_825f_587a3564c064_c1)'>\\n   <text x='18.54' y='235.03' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='18.54' y='170.06' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>60<\\/text>\\n   <text x='18.54' y='105.09' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>70<\\/text>\\n   <text x='18.54' y='40.12' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>80<\\/text>\\n   <polyline points='30.53,231.87 33.27,231.87' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,166.90 33.27,166.90' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,101.94 33.27,101.94' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='30.53,36.97 33.27,36.97' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='88.22,259.01 88.22,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='158.68,259.01 158.68,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='229.13,259.01 229.13,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='299.59,259.01 299.59,256.27' fill='none' stroke='#333333' stroke-opacity='1' stroke-width='1.07' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <text x='83.33' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>25<\\/text>\\n   <text x='153.78' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>50<\\/text>\\n   <text x='224.24' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>75<\\/text>\\n   <text x='292.24' y='267.5' font-size='6.6pt' font-family='Helvetica' fill='#4D4D4D' fill-opacity='1'>100<\\/text>\\n   <text x='123.55' y='280.09' font-size='8.25pt' font-family='Helvetica'>FemaleLiteracyRate<\\/text>\\n   <text transform='translate(13.37,176.43) rotate(-90.00)' font-size='8.25pt' font-family='Helvetica'>LifeExpectancyYrs<\\/text>\\n   <rect x='323.23' y='74.29' width='103.29' height='113.16' fill='#FFFFFF' fill-opacity='1' stroke='none'/>\\n   <text x='328.71' y='88.88' font-size='8.25pt' font-family='Helvetica'>FoodSupplykcPPD<\\/text>\\n   <image x='328.71' y='95.57' width='17.28' height='86.4' preserveAspectRatio='none' xlink:href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAEsCAYAAAACUNnVAAAAmElEQVQ4ja2UQRLDMAgDd3hk/tnX5agcknFaCoa0vnkMCEnGsL12GQhDYDpPwoDrpBFlRDWi/9Wu6AHC9FkLYLrzlhD3oJ3mDvRHRYy7IC8A7bCK8gpWKYDzeQVArDcDyD2YAnSofZvzaOA6Q7Oahp/dmRuVTQ0xU5TGP2o8Waool1obVuv1q8qP9xPvg633XlGLDtfIhNUBcBeA5ss0BXMAAAAASUVORK5CYII=' xmlns:xlink='http://www.w3.org/1999/xlink'/>\\n   <polyline points='342.53,181.83 345.99,181.83' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='342.53,160.30 345.99,160.30' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='342.53,138.77 345.99,138.77' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='342.53,117.25 345.99,117.25' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='342.53,95.72 345.99,95.72' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='332.16,181.83 328.71,181.83' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='332.16,160.30 328.71,160.30' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='332.16,138.77 328.71,138.77' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='332.16,117.25 328.71,117.25' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <polyline points='332.16,95.72 328.71,95.72' fill='none' stroke='#FFFFFF' stroke-opacity='1' stroke-width='0.37' stroke-linejoin='round' stroke-linecap='butt'/>\\n   <text x='351.47' y='184.98' font-size='6.6pt' font-family='Helvetica'>2000<\\/text>\\n   <text x='351.47' y='163.46' font-size='6.6pt' font-family='Helvetica'>2500<\\/text>\\n   <text x='351.47' y='141.93' font-size='6.6pt' font-family='Helvetica'>3000<\\/text>\\n   <text x='351.47' y='120.4' font-size='6.6pt' font-family='Helvetica'>3500<\\/text>\\n   <text x='351.47' y='98.87' font-size='6.6pt' font-family='Helvetica'>4000<\\/text>\\n  <\\/g>\\n <\\/g>\\n<\\/svg>\",\"js\":null,\"uid\":\"svg_19208998_de5f_480d_825f_587a3564c064\",\"ratio\":1.5,\"settings\":{\"tooltip\":{\"css\":\".tooltip_SVGID_ { background-color:white;font-style:italic;padding:10px;border-radius:10px 20px 10px 20px; ; position:absolute;pointer-events:none;z-index:999;}\",\"placement\":\"doc\",\"opacity\":0.75,\"offx\":10,\"offy\":0,\"use_cursor_pos\":true,\"use_fill\":false,\"use_stroke\":false,\"delay_over\":200,\"delay_out\":500},\"hover\":{\"css\":\".hover_data_SVGID_ { r:4px;cursor:pointer;stroke:red;stroke-width:2px; }\",\"reactive\":false,\"nearest_distance\":null},\"hover_inv\":{\"css\":\"\"},\"hover_key\":{\"css\":\".hover_key_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_key_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_key_SVGID_ { fill:orange;stroke:black; }\\nline.hover_key_SVGID_, polyline.hover_key_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_key_SVGID_, polygon.hover_key_SVGID_, path.hover_key_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_key_SVGID_ { stroke:orange; }\",\"reactive\":true},\"hover_theme\":{\"css\":\".hover_theme_SVGID_ { fill:orange;stroke:black;cursor:pointer; }\\ntext.hover_theme_SVGID_ { stroke:none;fill:orange; }\\ncircle.hover_theme_SVGID_ { fill:orange;stroke:black; }\\nline.hover_theme_SVGID_, polyline.hover_theme_SVGID_ { fill:none;stroke:orange; }\\nrect.hover_theme_SVGID_, polygon.hover_theme_SVGID_, path.hover_theme_SVGID_ { fill:orange;stroke:none; }\\nimage.hover_theme_SVGID_ { stroke:orange; }\",\"reactive\":true},\"select\":{\"css\":\".select_data_SVGID_ { fill:#FF3333;stroke:black; }\",\"type\":\"multiple\",\"only_shiny\":true,\"selected\":[]},\"select_inv\":{\"css\":\"\"},\"select_key\":{\"css\":\".select_key_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_key_SVGID_ { stroke:none;fill:red; }\\ncircle.select_key_SVGID_ { fill:red;stroke:black; }\\nline.select_key_SVGID_, polyline.select_key_SVGID_ { fill:none;stroke:red; }\\nrect.select_key_SVGID_, polygon.select_key_SVGID_, path.select_key_SVGID_ { fill:red;stroke:none; }\\nimage.select_key_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"select_theme\":{\"css\":\".select_theme_SVGID_ { fill:red;stroke:black;cursor:pointer; }\\ntext.select_theme_SVGID_ { stroke:none;fill:red; }\\ncircle.select_theme_SVGID_ { fill:red;stroke:black; }\\nline.select_theme_SVGID_, polyline.select_theme_SVGID_ { fill:none;stroke:red; }\\nrect.select_theme_SVGID_, polygon.select_theme_SVGID_, path.select_theme_SVGID_ { fill:red;stroke:none; }\\nimage.select_theme_SVGID_ { stroke:red; }\",\"type\":\"single\",\"only_shiny\":true,\"selected\":[]},\"zoom\":{\"min\":1,\"max\":10,\"duration\":300},\"toolbar\":{\"position\":\"topright\",\"pngname\":\"diagram\",\"tooltips\":null,\"fixed\":false,\"hidden\":[],\"delay_over\":200,\"delay_out\":500},\"sizing\":{\"rescale\":true,\"width\":1}}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n:::\n:::\n\n## Model with interaction between *two continuous variables*\n\nModel we are fitting:\n\n$$ LE = \\beta_0 + \\beta_1 FLR^c + \\beta_2 FS^c + \\beta_3 FLR^c \\cdot FS^c + \\epsilon$$\n\n-   $LE$ as life expectancy\n-   $FLR^c$ as the **centered** around the mean female literacy rate (continuous variable)\n-   $FS^c$ as the **centered** around the mean food supply (continuous variable)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Code to center FLR and FS\"}\ngapm_sub = gapm_sub %>% \n  mutate(FLR_c = FemaleLiteracyRate - mean(FemaleLiteracyRate), \n         FS_c = FoodSupplykcPPD - mean(FoodSupplykcPPD))\nmean_FS = mean(gapm_sub$FoodSupplykcPPD) %>% round(digits = 0)\nmean_FLR = mean(gapm_sub$FemaleLiteracyRate) %>% round(digits = 2)\n```\n:::\n\n\nIn R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_fs = lm(LifeExpectancyYrs ~ FLR_c + FS_c + FLR_c*FS_c, data = gapm_sub)\n```\n:::\n\n\nOR\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_fs = lm(LifeExpectancyYrs ~ FLR_c*FS_c, data = gapm_sub)\n```\n:::\n\n\n## Displaying the regression table and writing fitted regression equation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy_m_fs = tidy(m_int_fs, conf.int=T) \ntidy_m_fs %>% gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 5)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"edtwgcysrg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#edtwgcysrg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#edtwgcysrg thead, #edtwgcysrg tbody, #edtwgcysrg tfoot, #edtwgcysrg tr, #edtwgcysrg td, #edtwgcysrg th {\n  border-style: none;\n}\n\n#edtwgcysrg p {\n  margin: 0;\n  padding: 0;\n}\n\n#edtwgcysrg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#edtwgcysrg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#edtwgcysrg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#edtwgcysrg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#edtwgcysrg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#edtwgcysrg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#edtwgcysrg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#edtwgcysrg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#edtwgcysrg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#edtwgcysrg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#edtwgcysrg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#edtwgcysrg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#edtwgcysrg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#edtwgcysrg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#edtwgcysrg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#edtwgcysrg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#edtwgcysrg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#edtwgcysrg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#edtwgcysrg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#edtwgcysrg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#edtwgcysrg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#edtwgcysrg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#edtwgcysrg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#edtwgcysrg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#edtwgcysrg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#edtwgcysrg .gt_left {\n  text-align: left;\n}\n\n#edtwgcysrg .gt_center {\n  text-align: center;\n}\n\n#edtwgcysrg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#edtwgcysrg .gt_font_normal {\n  font-weight: normal;\n}\n\n#edtwgcysrg .gt_font_bold {\n  font-weight: bold;\n}\n\n#edtwgcysrg .gt_font_italic {\n  font-style: italic;\n}\n\n#edtwgcysrg .gt_super {\n  font-size: 65%;\n}\n\n#edtwgcysrg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#edtwgcysrg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#edtwgcysrg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#edtwgcysrg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#edtwgcysrg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#edtwgcysrg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#edtwgcysrg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#edtwgcysrg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#edtwgcysrg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">70.32060</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.72393</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">97.13721</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00000</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">68.87601</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">71.76518</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FLR_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.15532</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.03808</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.07905</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00012</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.07934</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.23130</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FS_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.00849</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00182</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">4.67908</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00001</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.00487</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.01212</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">FLR_c:FS_c</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">−0.00001</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00008</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">−0.06908</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.94513</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">−0.00016</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.00015</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\widehat\\beta_2 FS^c + \\widehat\\beta_3 FLR^c \\cdot FS^c \\\\\n\\widehat{LE} = & 70.32 + 0.16 \\cdot FLR^c + 0.01 \\cdot FS^c - 0.00001 \\cdot FLR^c \\cdot FS^c\n\\end{aligned}$$\n\n## Comparing fitted regression lines for various food supply values\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\widehat\\beta_2 FS^c + \\widehat\\beta_3 FLR^c \\cdot FS^c \\\\\n\\widehat{LE} = & 70.32 + 0.16 \\cdot FLR^c + 0.01 \\cdot FS^c - 0.00001 \\cdot FLR^c \\cdot FS^c\n\\end{aligned}$$\n\nTo identify different lines, we need to pick example values of Food Supply:\n\n::: columns\n::: {.column width=\"33%\"}\n::: FS1\n::: FS1-title\nFood Supply of 1812 kcal PPD\n:::\n\n::: FS1-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\\\ & \\widehat\\beta_2 \\cdot (-1000) + \\\\ & \\widehat\\beta_3 FLR^c \\cdot (-1000) \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 - 1000 \\widehat\\beta_2 \\big)+ \\\\ & \\big(\\widehat\\beta_1 - 1000 \\widehat\\beta_3  \\big) FLR^c\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: FS2\n::: FS2-title\nFood Supply of 2812 kcal PPD\n:::\n\n::: FS2-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\\\ & \\widehat\\beta_2 \\cdot 0 + \\\\ & \\widehat\\beta_3 FLR^c \\cdot 0 \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 \\big)+ \\\\ & \\big(\\widehat\\beta_1 \\big) FLR^c\n\\end{aligned}$$\n:::\n:::\n:::\n\n::: {.column width=\"33%\"}\n::: FS3\n::: FS3-title\nFood Supply of 3812 kcal PPD\n:::\n\n::: FS3-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\\\ & \\widehat\\beta_2 \\cdot 1000 + \\\\ & \\widehat\\beta_3 FLR^c \\cdot 1000 \\\\\n\\widehat{LE} = & \\big(\\widehat\\beta_0 + 1000 \\widehat\\beta_2 \\big)+ \\\\ & \\big(\\widehat\\beta_1 + 1000 \\widehat\\beta_3  \\big) FLR^c\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Poll Everywhere Question??\n\n## Interpretation for interaction between two continuous variables\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR^c + \\widehat\\beta_2 FS^c + \\widehat\\beta_3 FLR^c \\cdot FS^c \\\\\n\\widehat{LE} = & \\bigg[\\widehat\\beta_0 + \\widehat\\beta_2 \\cdot FS^c \\bigg] + \\underbrace{\\bigg[\\widehat\\beta_1 + \\widehat\\beta_3 \\cdot FS^c \\bigg]}_\\text{FLR's effect} FLR \\\\\n\\end{aligned}$$\n\n-   Interpretation:\n\n    -   $\\beta_3$ = mean change in female literacy rate's effect, for every one kcal PPD increase in food supply\n\n-   In summary, the interaction term can be interpreted as \"difference in adjusted female literacy rate effect for every 1 kcal PPD increase in food supply\"\n\n-   It will be helpful to test the interaction to round out this interpretation!!\n\n## Test interaction between two continuous variables\n\n-   We run an F-test for a single coefficients ($\\beta_3$) in the below model (see lesson 9)\n\n$$ LE = \\beta_0 + \\beta_1 FLR^c + \\beta_2 FS^c + \\beta_3 FLR^c \\cdot FS^c + \\epsilon$$\n\n::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"40%\"}\n::: proof1\n::: proof-title\nNull $H_0$\n:::\n\n::: proof-cont\n$$\\beta_3=0$$\n:::\n:::\n:::\n\n::: {.column width=\"40%\"}\n::: definition\n::: def-title\nAlternative $H_1$\n:::\n\n::: def-cont\n$$\\beta_3\\neq0$$\n:::\n:::\n:::\n\n::: {.column width=\"10%\"}\n:::\n:::\n\n::: columns\n::: {.column width=\"10%\"}\n:::\n\n::: {.column width=\"40%\"}\n::: proof1\n::: proof-title\nNull / Smaller / Reduced model\n:::\n\n::: proof-cont\n$$ LE = \\beta_0 + \\beta_1 FLR^c + \\beta_2 FS^c + \\epsilon$$\n:::\n:::\n:::\n\n::: {.column width=\"40%\"}\n::: definition\n::: def-title\nAlternative / Larger / Full model\n:::\n\n::: def-cont\n$$\\begin{aligned}\nLE = & \\beta_0 + \\beta_1 FLR^c + \\beta_2 FS^c + \\\\ & \\beta_3 FLR^c \\cdot FS^c + \\epsilon\n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Test interaction between two continuous variables\n\n-   Fit the reduced and full model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_fs_red = lm(LifeExpectancyYrs ~ FLR_c + FS_c, \n                   data = gapm_sub)\nm_int_fs_full = lm(LifeExpectancyYrs ~ FLR_c + FS_c +\n                  FLR_c*FS_c, data = gapm_sub)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Display the ANOVA table with F-statistic and p-value\"}\nanova(m_int_fs_red, m_int_fs_full) %>% tidy() %>% \n  gt() %>% tab_options(table.font.size = 35) %>% fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"nejijcehnh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#nejijcehnh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#nejijcehnh thead, #nejijcehnh tbody, #nejijcehnh tfoot, #nejijcehnh tr, #nejijcehnh td, #nejijcehnh th {\n  border-style: none;\n}\n\n#nejijcehnh p {\n  margin: 0;\n  padding: 0;\n}\n\n#nejijcehnh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 35px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#nejijcehnh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#nejijcehnh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#nejijcehnh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#nejijcehnh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#nejijcehnh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#nejijcehnh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#nejijcehnh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#nejijcehnh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#nejijcehnh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#nejijcehnh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#nejijcehnh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#nejijcehnh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#nejijcehnh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#nejijcehnh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nejijcehnh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#nejijcehnh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#nejijcehnh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#nejijcehnh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nejijcehnh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#nejijcehnh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nejijcehnh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#nejijcehnh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nejijcehnh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#nejijcehnh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#nejijcehnh .gt_left {\n  text-align: left;\n}\n\n#nejijcehnh .gt_center {\n  text-align: center;\n}\n\n#nejijcehnh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#nejijcehnh .gt_font_normal {\n  font-weight: normal;\n}\n\n#nejijcehnh .gt_font_bold {\n  font-weight: bold;\n}\n\n#nejijcehnh .gt_font_italic {\n  font-style: italic;\n}\n\n#nejijcehnh .gt_super {\n  font-size: 65%;\n}\n\n#nejijcehnh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#nejijcehnh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#nejijcehnh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#nejijcehnh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#nejijcehnh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#nejijcehnh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#nejijcehnh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#nejijcehnh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#nejijcehnh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df.residual\">df.residual</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rss\">rss</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FLR_c + FS_c</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">69.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,005.556</td>\n<td headers=\"df\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">LifeExpectancyYrs ~ FLR_c + FS_c + FLR_c * FS_c</td>\n<td headers=\"df.residual\" class=\"gt_row gt_right\">68.000</td>\n<td headers=\"rss\" class=\"gt_row gt_right\">2,005.415</td>\n<td headers=\"df\" class=\"gt_row gt_right\">1.000</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">0.141</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.005</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.945</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n-   Conclusion: There is not a significant interaction between female literacy rate and food supply (p = 0.945). Food supply is not an effect modifier of the association between female literacy rate and life expectancy.\n\n# Learning Objective\n\n**Bonus learning objective that's not really bonus but just a last minute addition**\n\n6. Report results for a best-fit line (with confidence intervals) at different levels of an effect measure modifier\n\n## How to find the confidence interval for each slope?\n\n- In the example with FS and FLR, we showed:\n\n::: FS3\n::: FS3-title\nBest-fit line for Food Supply of 3812 kcal PPD\n:::\n::: FS3-cont\n$$\\begin{aligned} \n\\widehat{LE} = & \\big(\\widehat\\beta_0 + 1000 \\widehat\\beta_2 \\big)+  \\big(\\widehat\\beta_1 + 1000 \\widehat\\beta_3  \\big) FLR^c\n\\end{aligned}$$\n:::\n:::\n\n- Often, we want to report the estimate of the combined coefficients: $\\widehat\\beta_1 + 1000 \\widehat\\beta_3$\n\n  - This allows us to make a statement like: \"At a food supply of 3812 kcal PPD, mean life expectancy increases ($\\widehat\\beta_1 + 1000 \\widehat\\beta_3$) years for every one percent increase in female literacy rate (95% CI: \\_\\_, \\_\\_).\"\n\n \n\n- We can calculate $\\widehat\\beta_1 + 1000 \\widehat\\beta_3$ by using the values of the estimated coefficients\n\n- BUT we always want to have a **95% confidence interval** when we report this combined estimate!!\n\n## Getting a 95% confidence interval requires linear combinations!\n\n- If we want a confidence interval for $\\widehat\\beta_1 + 1000 \\widehat\\beta_3$, then we would use the formula:\n\n$$\\bigg(\\widehat\\beta_1 + 1000 \\widehat\\beta_3 \\bigg) \\pm t^* \\times SE_{(\\beta_1 + 1000 \\beta_3)}$$\n\n- The hard part is figuring out what $SE_{(\\beta_1 + 1000 \\beta_3)}$ (or $\\text{Var}(\\beta_1 + 1000 \\beta_3)$) equals\n\n- We need to go back to variance of linear combinations (BSTA 512/612, EPI 525):\n$$\\text{Var}(aX + bY) = a^2\\text{Var}(X) + b^2\\text{Var}(Y) + 2ab\\text{Cov}(X, Y)$$\nor\n$$\\text{Var}(aX - bY) = a^2\\text{Var}(X) + b^2\\text{Var}(Y) - 2ab\\text{Cov}(X, Y)$$\n\n## Reference: calculating $SE_{(\\beta_1 + 1000 \\beta_3)}$ by hand\n\n- A helpful function that returns the variance-covariance matric of all the coefficients in model `m_int_fs`:\n\n::: columns\n::: {.column width=\"70%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nvcov(m_int_fs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              (Intercept)         FLR_c          FS_c    FLR_c:FS_c\n(Intercept)  5.240754e-01 -6.771205e-03  5.586960e-05 -2.609611e-05\nFLR_c       -6.771205e-03  1.449828e-03 -3.150719e-05  1.543619e-06\nFS_c         5.586960e-05 -3.150719e-05  3.294981e-06 -1.273649e-08\nFLR_c:FS_c  -2.609611e-05  1.543619e-06 -1.273649e-08  5.949082e-09\n```\n:::\n:::\n\n:::\n::: {.column width=\"30%\"}\n$$ \\begin{aligned}\n\\text{Var}(\\beta_1) & = 0.0014498 \\\\\n\\text{Var}(\\beta_3) & = 6\\times 10^{-9} \\\\\n\\text{Cov}(\\beta_1, \\beta_3) & = 1.544\\times 10^{-6} \\\\\n\\end{aligned}$$\n:::\n:::\n\n$$ \\begin{aligned}\n\\text{Var}(\\beta_1 + 1000 \\beta_3) & = \\text{Var}(\\beta_1) + 1000^2\\text{Var}(\\beta_3) + 2000\\text{Cov}(\\beta_1, \\beta_3) \\\\ \n\\text{Var}(\\beta_1 + 1000 \\beta_3) & = 0.0014498 + 1000^2 \\times 6\\times 10^{-9} + 2000 \\times 1.544\\times 10^{-6} \\\\ \n\\text{Var}(\\beta_1 + 1000 \\beta_3) & = 0.0104861 \\\\\nSE_{(\\beta_1 + 1000 \\beta_3)} & = \\sqrt{0.0104861} \\\\ \nSE_{(\\beta_1 + 1000 \\beta_3)} & = 0.1024019\n\\end{aligned}$$\n\n\n## We can use R and `estimable()` to find the estimate and CI\n\nFor $\\widehat\\beta_1 + 1000 \\widehat\\beta_3$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gmodels)\nm_int_fs %>% estimable(\n                   c(\"(Intercept)\" = 0,      # beta0\n                     \"FLR_c\"       = 1,      # beta1\n                     \"FS_c\"        = 0,      # beta2\n                     \"FLR_c:FS_c\"  = 1000),  # beta3\n                   conf.int = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Estimate Std. Error  t value DF  Pr(>|t|)    Lower.CI  Upper.CI\n(0 1 0 1000) 0.1499879  0.1024019 1.464698 68 0.1476115 -0.05435192 0.3543277\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n \n\n**Our conclusion:** At a food supply of 3812 kcal PPD, mean life expectancy increases 0.14999 years for every one percent increase in female literacy rate (95% CI: -0.05435, 0.35433).\n\n## Another example: income (binary) and FLR (1/2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_inc2 = gapm_sub %>% \n  lm(formula = LifeExpectancyYrs ~ FLR_c*income_levels2)\n```\n:::\n\n\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR + \\widehat\\beta_2 I(\\text{high income}) + \\widehat\\beta_3 FLR \\cdot I(\\text{high income}) \\\\\n\\widehat{LE} = & 54.85 + 0.156 \\cdot FLR - 16.65 \\cdot I(\\text{high income}) + 0.228 \\cdot FLR \\cdot I(\\text{high income})\n\\end{aligned}$$\n\n::: columns\n::: column\n::: proof1\n::: proof-title\nFor lower income countries: $I(\\text{high income}) =0$\n:::\n\n::: proof-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR + \\widehat\\beta_2 \\cdot 0 + \\widehat\\beta_3 FLR \\cdot 0 \\\\\n\\widehat{LE} = & 54.85 + 0.156 \\cdot FLR - 16.65 \\cdot 0 + \\\\\n& 0.228 \\cdot FLR \\cdot 0 \\\\ \n\\widehat{LE} = & 54.85 + 0.156 \\cdot FLR\\\\ \n\\end{aligned}$$\n:::\n:::\n:::\n\n::: column\n::: fact\n::: fact-title\nFor higher income countries: $I(\\text{high income}) =1$\n:::\n\n::: fact-cont\n$$ \\begin{aligned}\n\\widehat{LE} = & \\widehat\\beta_0 + \\widehat\\beta_1 FLR + \\widehat\\beta_2 \\cdot 1 + \\widehat\\beta_3 FLR \\cdot 1 \\\\\n\\widehat{LE} = & 54.85 + 0.156 \\cdot FLR - 16.65 \\cdot 1 + \\\\ & 0.228 \\cdot FLR \\cdot 1 \\\\ \n\\widehat{LE} = & 38.2 + 0.384 \\cdot FLR\\\\ \n\\end{aligned}$$\n:::\n:::\n:::\n:::\n\n## Another example: income (binary) and FLR (2/2)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_int_inc2$coefficients # I just need to see the exact names\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      (Intercept)                             FLR_c \n                       67.6818102                         0.1564398 \n      income_levels2Higher income FLR_c:income_levels2Higher income \n                        2.0729925                         0.2282290 \n```\n:::\n\n```{.r .cell-code}\nm_int_inc2 %>% estimable(\n                   c(\"(Intercept)\" = 0,      # beta0\n                     \"FLR_c\"       = 1,      # beta1\n                     \"income_levels2Higher income\" = 0,      # beta2\n                     \"FLR_c:income_levels2Higher income\"  = 1),  # beta3\n                   conf.int = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           Estimate Std. Error  t value DF   Pr(>|t|)   Lower.CI  Upper.CI\n(0 1 0 1) 0.3846688  0.1591843 2.416499 68 0.01836001 0.06702138 0.7023161\n```\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n \n\n**Our conclusion:** For countries with high income, mean life expectancy increases 0.385 years for every one percent increase in female literacy rate (95% CI: 0.067, 0.702).\n\n## If our example had an effect measure modifier\n\n\n::: {.cell}\n\n:::\n\n\n- None of our examples had a significant interaction, so it's hard to demonstrate exactly how we would report this\n\n- Let's say, **just for example**, that income had a significant interaction with FLR\n  - How would we report this to an audience??\n  \n- Here's how to report on an interaction/EMM:\n\n  - We found that a country's income status (high or low) is a significant effect measure modifier on female literacy rate (*include p-value for interaction test here*). For countries with high income, mean life expectancy increases 0.385 years for every one percent increase in female literacy rate (95% CI: 0.067, 0.702). For countries with low income, mean life expectancy increases 2.073 years for every one percent increase in female literacy rate (95% CI: -2.922, 7.068).\"\n\n# Extra Reference Material\n\n## General interpretation of the interaction term (reference)\n\n$E[Y\\mid X_{1},X_{2} ]=\\beta_0 + \\underbrace{(\\beta_1+\\beta_3X_{2}) }_\\text{$X_{1}$'s effect} X_{1}+ \\underbrace{\\beta_2X_{2}}_\\text{$X_{2}$ held constant}$\\\n${\\color{white}{E[Y\\mid X_{1},X_{2} ]}}=\\beta_0 + \\underbrace{(\\beta_2+\\beta_3X_{1}) }_\\text{$X_{2}$'s effect}X_{2} + \\underbrace{\\beta_1X_{1}}_\\text{$X_{1}$ held constant}$\n\n-   Interpretation:\n\n    -   $\\beta_3$ = mean change in $X_{1}$'s effect, per unit increase in $X_{2}$;\\\n\n    -   [$\\beta_3$]{style=\"color: white\"} = mean change in $X_{2}$'s effect, per unit increase in $X_{1}$;\n\n    -   where the \"$X_{1}$ effect\" equals the change in $E[Y]$ per unit increase in $X_{1}$ with $X_{2}$ held constant, i.e. \"adjusted $X_{1}$ effect\"\n\n-   In summary, the interaction term can be interpreted as \"difference in adjusted $X_1$ (or $X_2$) effect per unit increase in $X_2$ (or $X_1$)\"\n\n## A glimpse at how interactions might be incorporated into model selection {.smaller}\n\n1.  Identify outcome (Y) and primary explanatory (X) variables\n\n2.  Decide which other variables might be important and could be potential confounders. Add these to the model.\n\n    -   This is often done by indentifying variables that previous research deemed important, or researchers believe could be important\n    -   From a statistical perspective, we often include variables that are significantly associated with the outcome (in their respective SLR)\n\n3.  (Optional step) Test 3 way interactions\n\n    -   This makes our model incredibly hard to interpret. Our class will not cover this!!\n    -   We will skip to testing 2 way interactions\n\n4.  Test 2 way interactions\n\n    -   When testing a 2 way interaction, make sure the full and reduced models contain the main effects\n\n    -   First test all the 2 way interactions together using a partial F-test (with $alpha = 0.10$)\n\n        -   If this test not significant, do not test 2-way interactions individually\n        -   If partial F-test is significant, then test each of the 2-way interactions\n\n5.  Remaining main effects - to include of not to include?\n\n    -   For variables that are included in any interactions, they will be automatically included as main effects and thus not checked for confounding\n\n    -   For variables that are not included in any interactions:\n\n        -   Check to see if they are confounders by seeing whether exclusion of the variable(s) changes any of the coefficient of the primary explanatory variable (including interactions) X by more than 10%\n\n            -   If any of X's coefficients change when removing the potential confounder, then keep it in the model\n",
    "supporting": [
      "12_Interactions_02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/d3-bundle-5.16.0/d3-bundle.min.js\"></script>\n<script src=\"../../site_libs/d3-lasso-0.0.5/d3-lasso.min.js\"></script>\n<script src=\"../../site_libs/save-svg-as-png-1.4.17/save-svg-as-png.min.js\"></script>\n<script src=\"../../site_libs/flatbush-4.4.0/flatbush.min.js\"></script>\n<link href=\"../../site_libs/ggiraphjs-0.8.10/ggiraphjs.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/ggiraphjs-0.8.10/ggiraphjs.min.js\"></script>\n<script src=\"../../site_libs/girafe-binding-0.8.10/girafe.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}